// Code generated by ent, DO NOT EDIT.

package desktopmemberapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldLTE(FieldID, id))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldMemberID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldAPIKeyID, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldAssignedAt, v))
}

// RetiredAt applies equality check predicate on the "retired_at" field. It's identical to RetiredAtEQ.
func RetiredAt(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldRetiredAt, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNotIn(FieldMemberID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldLTE(FieldAssignedAt, v))
}

// RetiredAtEQ applies the EQ predicate on the "retired_at" field.
func RetiredAtEQ(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldEQ(FieldRetiredAt, v))
}

// RetiredAtNEQ applies the NEQ predicate on the "retired_at" field.
func RetiredAtNEQ(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNEQ(FieldRetiredAt, v))
}

// RetiredAtIn applies the In predicate on the "retired_at" field.
func RetiredAtIn(vs ...time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldIn(FieldRetiredAt, vs...))
}

// RetiredAtNotIn applies the NotIn predicate on the "retired_at" field.
func RetiredAtNotIn(vs ...time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNotIn(FieldRetiredAt, vs...))
}

// RetiredAtGT applies the GT predicate on the "retired_at" field.
func RetiredAtGT(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldGT(FieldRetiredAt, v))
}

// RetiredAtGTE applies the GTE predicate on the "retired_at" field.
func RetiredAtGTE(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldGTE(FieldRetiredAt, v))
}

// RetiredAtLT applies the LT predicate on the "retired_at" field.
func RetiredAtLT(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldLT(FieldRetiredAt, v))
}

// RetiredAtLTE applies the LTE predicate on the "retired_at" field.
func RetiredAtLTE(v time.Time) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldLTE(FieldRetiredAt, v))
}

// RetiredAtIsNil applies the IsNil predicate on the "retired_at" field.
func RetiredAtIsNil() predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldIsNull(FieldRetiredAt))
}

// RetiredAtNotNil applies the NotNil predicate on the "retired_at" field.
func RetiredAtNotNil() predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.FieldNotNull(FieldRetiredAt))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.DesktopMember) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DesktopMemberAPIKey) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DesktopMemberAPIKey) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DesktopMemberAPIKey) predicate.DesktopMemberAPIKey {
	return predicate.DesktopMemberAPIKey(sql.NotPredicates(p))
}
