// Code generated by ent, DO NOT EDIT.

package desktopconversationrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldID, id))
}

// RecordID applies equality check predicate on the "record_id" field. It's identical to RecordIDEQ.
func RecordID(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldRecordID, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldOrganizationID, v))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldMemberID, v))
}

// InstallationID applies equality check predicate on the "installation_id" field. It's identical to InstallationIDEQ.
func InstallationID(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldInstallationID, v))
}

// Client applies equality check predicate on the "client" field. It's identical to ClientEQ.
func Client(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldClient, v))
}

// SourceSessionID applies equality check predicate on the "source_session_id" field. It's identical to SourceSessionIDEQ.
func SourceSessionID(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldSourceSessionID, v))
}

// SourceTurnID applies equality check predicate on the "source_turn_id" field. It's identical to SourceTurnIDEQ.
func SourceTurnID(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldSourceTurnID, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldStartedAt, v))
}

// StoppedAt applies equality check predicate on the "stopped_at" field. It's identical to StoppedAtEQ.
func StoppedAt(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldStoppedAt, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldReceivedAt, v))
}

// Cwd applies equality check predicate on the "cwd" field. It's identical to CwdEQ.
func Cwd(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldCwd, v))
}

// CaptureStatus applies equality check predicate on the "capture_status" field. It's identical to CaptureStatusEQ.
func CaptureStatus(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldCaptureStatus, v))
}

// PromptCount applies equality check predicate on the "prompt_count" field. It's identical to PromptCountEQ.
func PromptCount(v int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldPromptCount, v))
}

// RecordIDEQ applies the EQ predicate on the "record_id" field.
func RecordIDEQ(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldRecordID, v))
}

// RecordIDNEQ applies the NEQ predicate on the "record_id" field.
func RecordIDNEQ(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldRecordID, v))
}

// RecordIDIn applies the In predicate on the "record_id" field.
func RecordIDIn(vs ...uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldRecordID, vs...))
}

// RecordIDNotIn applies the NotIn predicate on the "record_id" field.
func RecordIDNotIn(vs ...uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldRecordID, vs...))
}

// RecordIDGT applies the GT predicate on the "record_id" field.
func RecordIDGT(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldRecordID, v))
}

// RecordIDGTE applies the GTE predicate on the "record_id" field.
func RecordIDGTE(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldRecordID, v))
}

// RecordIDLT applies the LT predicate on the "record_id" field.
func RecordIDLT(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldRecordID, v))
}

// RecordIDLTE applies the LTE predicate on the "record_id" field.
func RecordIDLTE(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldRecordID, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldMemberID, vs...))
}

// InstallationIDEQ applies the EQ predicate on the "installation_id" field.
func InstallationIDEQ(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldInstallationID, v))
}

// InstallationIDNEQ applies the NEQ predicate on the "installation_id" field.
func InstallationIDNEQ(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldInstallationID, v))
}

// InstallationIDIn applies the In predicate on the "installation_id" field.
func InstallationIDIn(vs ...uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldInstallationID, vs...))
}

// InstallationIDNotIn applies the NotIn predicate on the "installation_id" field.
func InstallationIDNotIn(vs ...uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldInstallationID, vs...))
}

// InstallationIDGT applies the GT predicate on the "installation_id" field.
func InstallationIDGT(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldInstallationID, v))
}

// InstallationIDGTE applies the GTE predicate on the "installation_id" field.
func InstallationIDGTE(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldInstallationID, v))
}

// InstallationIDLT applies the LT predicate on the "installation_id" field.
func InstallationIDLT(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldInstallationID, v))
}

// InstallationIDLTE applies the LTE predicate on the "installation_id" field.
func InstallationIDLTE(v uuid.UUID) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldInstallationID, v))
}

// ClientEQ applies the EQ predicate on the "client" field.
func ClientEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldClient, v))
}

// ClientNEQ applies the NEQ predicate on the "client" field.
func ClientNEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldClient, v))
}

// ClientIn applies the In predicate on the "client" field.
func ClientIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldClient, vs...))
}

// ClientNotIn applies the NotIn predicate on the "client" field.
func ClientNotIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldClient, vs...))
}

// ClientGT applies the GT predicate on the "client" field.
func ClientGT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldClient, v))
}

// ClientGTE applies the GTE predicate on the "client" field.
func ClientGTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldClient, v))
}

// ClientLT applies the LT predicate on the "client" field.
func ClientLT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldClient, v))
}

// ClientLTE applies the LTE predicate on the "client" field.
func ClientLTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldClient, v))
}

// ClientContains applies the Contains predicate on the "client" field.
func ClientContains(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContains(FieldClient, v))
}

// ClientHasPrefix applies the HasPrefix predicate on the "client" field.
func ClientHasPrefix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasPrefix(FieldClient, v))
}

// ClientHasSuffix applies the HasSuffix predicate on the "client" field.
func ClientHasSuffix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasSuffix(FieldClient, v))
}

// ClientEqualFold applies the EqualFold predicate on the "client" field.
func ClientEqualFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEqualFold(FieldClient, v))
}

// ClientContainsFold applies the ContainsFold predicate on the "client" field.
func ClientContainsFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContainsFold(FieldClient, v))
}

// SourceSessionIDEQ applies the EQ predicate on the "source_session_id" field.
func SourceSessionIDEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldSourceSessionID, v))
}

// SourceSessionIDNEQ applies the NEQ predicate on the "source_session_id" field.
func SourceSessionIDNEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldSourceSessionID, v))
}

// SourceSessionIDIn applies the In predicate on the "source_session_id" field.
func SourceSessionIDIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldSourceSessionID, vs...))
}

// SourceSessionIDNotIn applies the NotIn predicate on the "source_session_id" field.
func SourceSessionIDNotIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldSourceSessionID, vs...))
}

// SourceSessionIDGT applies the GT predicate on the "source_session_id" field.
func SourceSessionIDGT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldSourceSessionID, v))
}

// SourceSessionIDGTE applies the GTE predicate on the "source_session_id" field.
func SourceSessionIDGTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldSourceSessionID, v))
}

// SourceSessionIDLT applies the LT predicate on the "source_session_id" field.
func SourceSessionIDLT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldSourceSessionID, v))
}

// SourceSessionIDLTE applies the LTE predicate on the "source_session_id" field.
func SourceSessionIDLTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldSourceSessionID, v))
}

// SourceSessionIDContains applies the Contains predicate on the "source_session_id" field.
func SourceSessionIDContains(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContains(FieldSourceSessionID, v))
}

// SourceSessionIDHasPrefix applies the HasPrefix predicate on the "source_session_id" field.
func SourceSessionIDHasPrefix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasPrefix(FieldSourceSessionID, v))
}

// SourceSessionIDHasSuffix applies the HasSuffix predicate on the "source_session_id" field.
func SourceSessionIDHasSuffix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasSuffix(FieldSourceSessionID, v))
}

// SourceSessionIDEqualFold applies the EqualFold predicate on the "source_session_id" field.
func SourceSessionIDEqualFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEqualFold(FieldSourceSessionID, v))
}

// SourceSessionIDContainsFold applies the ContainsFold predicate on the "source_session_id" field.
func SourceSessionIDContainsFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContainsFold(FieldSourceSessionID, v))
}

// SourceTurnIDEQ applies the EQ predicate on the "source_turn_id" field.
func SourceTurnIDEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldSourceTurnID, v))
}

// SourceTurnIDNEQ applies the NEQ predicate on the "source_turn_id" field.
func SourceTurnIDNEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldSourceTurnID, v))
}

// SourceTurnIDIn applies the In predicate on the "source_turn_id" field.
func SourceTurnIDIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldSourceTurnID, vs...))
}

// SourceTurnIDNotIn applies the NotIn predicate on the "source_turn_id" field.
func SourceTurnIDNotIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldSourceTurnID, vs...))
}

// SourceTurnIDGT applies the GT predicate on the "source_turn_id" field.
func SourceTurnIDGT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldSourceTurnID, v))
}

// SourceTurnIDGTE applies the GTE predicate on the "source_turn_id" field.
func SourceTurnIDGTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldSourceTurnID, v))
}

// SourceTurnIDLT applies the LT predicate on the "source_turn_id" field.
func SourceTurnIDLT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldSourceTurnID, v))
}

// SourceTurnIDLTE applies the LTE predicate on the "source_turn_id" field.
func SourceTurnIDLTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldSourceTurnID, v))
}

// SourceTurnIDContains applies the Contains predicate on the "source_turn_id" field.
func SourceTurnIDContains(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContains(FieldSourceTurnID, v))
}

// SourceTurnIDHasPrefix applies the HasPrefix predicate on the "source_turn_id" field.
func SourceTurnIDHasPrefix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasPrefix(FieldSourceTurnID, v))
}

// SourceTurnIDHasSuffix applies the HasSuffix predicate on the "source_turn_id" field.
func SourceTurnIDHasSuffix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasSuffix(FieldSourceTurnID, v))
}

// SourceTurnIDIsNil applies the IsNil predicate on the "source_turn_id" field.
func SourceTurnIDIsNil() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIsNull(FieldSourceTurnID))
}

// SourceTurnIDNotNil applies the NotNil predicate on the "source_turn_id" field.
func SourceTurnIDNotNil() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotNull(FieldSourceTurnID))
}

// SourceTurnIDEqualFold applies the EqualFold predicate on the "source_turn_id" field.
func SourceTurnIDEqualFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEqualFold(FieldSourceTurnID, v))
}

// SourceTurnIDContainsFold applies the ContainsFold predicate on the "source_turn_id" field.
func SourceTurnIDContainsFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContainsFold(FieldSourceTurnID, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldStartedAt, v))
}

// StoppedAtEQ applies the EQ predicate on the "stopped_at" field.
func StoppedAtEQ(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldStoppedAt, v))
}

// StoppedAtNEQ applies the NEQ predicate on the "stopped_at" field.
func StoppedAtNEQ(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldStoppedAt, v))
}

// StoppedAtIn applies the In predicate on the "stopped_at" field.
func StoppedAtIn(vs ...time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldStoppedAt, vs...))
}

// StoppedAtNotIn applies the NotIn predicate on the "stopped_at" field.
func StoppedAtNotIn(vs ...time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldStoppedAt, vs...))
}

// StoppedAtGT applies the GT predicate on the "stopped_at" field.
func StoppedAtGT(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldStoppedAt, v))
}

// StoppedAtGTE applies the GTE predicate on the "stopped_at" field.
func StoppedAtGTE(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldStoppedAt, v))
}

// StoppedAtLT applies the LT predicate on the "stopped_at" field.
func StoppedAtLT(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldStoppedAt, v))
}

// StoppedAtLTE applies the LTE predicate on the "stopped_at" field.
func StoppedAtLTE(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldStoppedAt, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldReceivedAt, v))
}

// CwdEQ applies the EQ predicate on the "cwd" field.
func CwdEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldCwd, v))
}

// CwdNEQ applies the NEQ predicate on the "cwd" field.
func CwdNEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldCwd, v))
}

// CwdIn applies the In predicate on the "cwd" field.
func CwdIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldCwd, vs...))
}

// CwdNotIn applies the NotIn predicate on the "cwd" field.
func CwdNotIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldCwd, vs...))
}

// CwdGT applies the GT predicate on the "cwd" field.
func CwdGT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldCwd, v))
}

// CwdGTE applies the GTE predicate on the "cwd" field.
func CwdGTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldCwd, v))
}

// CwdLT applies the LT predicate on the "cwd" field.
func CwdLT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldCwd, v))
}

// CwdLTE applies the LTE predicate on the "cwd" field.
func CwdLTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldCwd, v))
}

// CwdContains applies the Contains predicate on the "cwd" field.
func CwdContains(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContains(FieldCwd, v))
}

// CwdHasPrefix applies the HasPrefix predicate on the "cwd" field.
func CwdHasPrefix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasPrefix(FieldCwd, v))
}

// CwdHasSuffix applies the HasSuffix predicate on the "cwd" field.
func CwdHasSuffix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasSuffix(FieldCwd, v))
}

// CwdIsNil applies the IsNil predicate on the "cwd" field.
func CwdIsNil() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIsNull(FieldCwd))
}

// CwdNotNil applies the NotNil predicate on the "cwd" field.
func CwdNotNil() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotNull(FieldCwd))
}

// CwdEqualFold applies the EqualFold predicate on the "cwd" field.
func CwdEqualFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEqualFold(FieldCwd, v))
}

// CwdContainsFold applies the ContainsFold predicate on the "cwd" field.
func CwdContainsFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContainsFold(FieldCwd, v))
}

// ResponseIsNil applies the IsNil predicate on the "response" field.
func ResponseIsNil() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIsNull(FieldResponse))
}

// ResponseNotNil applies the NotNil predicate on the "response" field.
func ResponseNotNil() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotNull(FieldResponse))
}

// CaptureStatusEQ applies the EQ predicate on the "capture_status" field.
func CaptureStatusEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldCaptureStatus, v))
}

// CaptureStatusNEQ applies the NEQ predicate on the "capture_status" field.
func CaptureStatusNEQ(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldCaptureStatus, v))
}

// CaptureStatusIn applies the In predicate on the "capture_status" field.
func CaptureStatusIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldCaptureStatus, vs...))
}

// CaptureStatusNotIn applies the NotIn predicate on the "capture_status" field.
func CaptureStatusNotIn(vs ...string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldCaptureStatus, vs...))
}

// CaptureStatusGT applies the GT predicate on the "capture_status" field.
func CaptureStatusGT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldCaptureStatus, v))
}

// CaptureStatusGTE applies the GTE predicate on the "capture_status" field.
func CaptureStatusGTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldCaptureStatus, v))
}

// CaptureStatusLT applies the LT predicate on the "capture_status" field.
func CaptureStatusLT(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldCaptureStatus, v))
}

// CaptureStatusLTE applies the LTE predicate on the "capture_status" field.
func CaptureStatusLTE(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldCaptureStatus, v))
}

// CaptureStatusContains applies the Contains predicate on the "capture_status" field.
func CaptureStatusContains(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContains(FieldCaptureStatus, v))
}

// CaptureStatusHasPrefix applies the HasPrefix predicate on the "capture_status" field.
func CaptureStatusHasPrefix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasPrefix(FieldCaptureStatus, v))
}

// CaptureStatusHasSuffix applies the HasSuffix predicate on the "capture_status" field.
func CaptureStatusHasSuffix(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldHasSuffix(FieldCaptureStatus, v))
}

// CaptureStatusEqualFold applies the EqualFold predicate on the "capture_status" field.
func CaptureStatusEqualFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEqualFold(FieldCaptureStatus, v))
}

// CaptureStatusContainsFold applies the ContainsFold predicate on the "capture_status" field.
func CaptureStatusContainsFold(v string) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldContainsFold(FieldCaptureStatus, v))
}

// PromptCountEQ applies the EQ predicate on the "prompt_count" field.
func PromptCountEQ(v int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldEQ(FieldPromptCount, v))
}

// PromptCountNEQ applies the NEQ predicate on the "prompt_count" field.
func PromptCountNEQ(v int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNEQ(FieldPromptCount, v))
}

// PromptCountIn applies the In predicate on the "prompt_count" field.
func PromptCountIn(vs ...int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldIn(FieldPromptCount, vs...))
}

// PromptCountNotIn applies the NotIn predicate on the "prompt_count" field.
func PromptCountNotIn(vs ...int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldNotIn(FieldPromptCount, vs...))
}

// PromptCountGT applies the GT predicate on the "prompt_count" field.
func PromptCountGT(v int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGT(FieldPromptCount, v))
}

// PromptCountGTE applies the GTE predicate on the "prompt_count" field.
func PromptCountGTE(v int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldGTE(FieldPromptCount, v))
}

// PromptCountLT applies the LT predicate on the "prompt_count" field.
func PromptCountLT(v int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLT(FieldPromptCount, v))
}

// PromptCountLTE applies the LTE predicate on the "prompt_count" field.
func PromptCountLTE(v int) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.FieldLTE(FieldPromptCount, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.DesktopOrganization) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.DesktopMember) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DesktopConversationRecord) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DesktopConversationRecord) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DesktopConversationRecord) predicate.DesktopConversationRecord {
	return predicate.DesktopConversationRecord(sql.NotPredicates(p))
}
