"""Generate the analysis response DTOs from the bundled API schemas."""
import json
from pathlib import Path

root = Path(__file__).parent
schemas = json.loads((root / 'schemas.json').read_text())['components']['schemas']
selected = '''UsageStats TokenTotals Comparison Finding Target EntitySummary FilterOption FrequencyBucket RetentionCohort RetentionCell TrendPoint Trend Adoption Overview AssetStats TokenAnalysis ModelTokens FeedbackAnalysis ComparisonRow MemberRow MemberDetail TeamDetail ApplicationRow ApplicationDetail SceneRow SceneDetail MetricDefinition KnowledgeRow KnowledgeDetail KnowledgeVersion VersionSummary CaseRow CaseDetail SourceDetail EvaluationRow EvaluationDetail EvaluationResult EvaluationSample SearchHit Favorite KnowledgeNote ReferenceEvidence ReportSummary ReportDetail ReportText Share SharedReport'''.split()
known = {'Id': 'string', 'TokenCount': 'string', 'Metric': 'Metric', 'Context': 'AnalysisContext', 'Filters': 'Filters', 'Range': 'DateRange'}
blocks = {}

def name(text):
    return ''.join({'id':'ID', 'ids':'IDs', 'ms':'MS'}.get(word, word.title()) for word in text.split('_'))

def go_type(schema, suggested):
    if '$ref' in schema:
        ref = schema['$ref'].split('/')[-1]
        if ref in known:
            return known[ref]
        emit(ref, schemas[ref])
        return ref
    if 'anyOf' in schema:
        variants = [v for v in schema['anyOf'] if v.get('type') != 'null']
        return '*' + go_type(variants[0], suggested)
    kind = schema.get('type')
    if isinstance(kind, list):
        return '*' + go_type({**schema, 'type': next(x for x in kind if x != 'null')}, suggested)
    if kind == 'array':
        return '[]' + go_type(schema['items'], suggested+'Item')
    if kind == 'object':
        emit(suggested, schema)
        return suggested
    return {'string':'string', 'integer':'int64', 'number':'float64', 'boolean':'bool'}[kind]

def emit(type_name, schema):
    if type_name in blocks:
        return
    blocks[type_name] = ''
    fields = []
    for field, value in schema['properties'].items():
        suffix = '' if field in schema.get('required', []) else ',omitempty'
        fields.append(f'\t{name(field)} {go_type(value, type_name+name(field))} `json:"{field}{suffix}"`')
    blocks[type_name] = 'type '+type_name+' struct {\n'+'\n'.join(fields)+'\n}\n'

for item in selected:
    emit(item, schemas[item])
(root / 'analysis_dto.go').write_text('// Code generated by generate_analysis_dto.py; DO NOT EDIT.\npackage bi\n\n'+'\n'.join(blocks.values()))
