// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopconversationrecord"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
	"github.com/google/uuid"
)

// DesktopConversationRecordCreate is the builder for creating a DesktopConversationRecord entity.
type DesktopConversationRecordCreate struct {
	config
	mutation *DesktopConversationRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRecordID sets the "record_id" field.
func (_c *DesktopConversationRecordCreate) SetRecordID(v uuid.UUID) *DesktopConversationRecordCreate {
	_c.mutation.SetRecordID(v)
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *DesktopConversationRecordCreate) SetOrganizationID(v int64) *DesktopConversationRecordCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetMemberID sets the "member_id" field.
func (_c *DesktopConversationRecordCreate) SetMemberID(v int64) *DesktopConversationRecordCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetInstallationID sets the "installation_id" field.
func (_c *DesktopConversationRecordCreate) SetInstallationID(v uuid.UUID) *DesktopConversationRecordCreate {
	_c.mutation.SetInstallationID(v)
	return _c
}

// SetClient sets the "client" field.
func (_c *DesktopConversationRecordCreate) SetClient(v string) *DesktopConversationRecordCreate {
	_c.mutation.SetClient(v)
	return _c
}

// SetSourceSessionID sets the "source_session_id" field.
func (_c *DesktopConversationRecordCreate) SetSourceSessionID(v string) *DesktopConversationRecordCreate {
	_c.mutation.SetSourceSessionID(v)
	return _c
}

// SetSourceTurnID sets the "source_turn_id" field.
func (_c *DesktopConversationRecordCreate) SetSourceTurnID(v string) *DesktopConversationRecordCreate {
	_c.mutation.SetSourceTurnID(v)
	return _c
}

// SetNillableSourceTurnID sets the "source_turn_id" field if the given value is not nil.
func (_c *DesktopConversationRecordCreate) SetNillableSourceTurnID(v *string) *DesktopConversationRecordCreate {
	if v != nil {
		_c.SetSourceTurnID(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *DesktopConversationRecordCreate) SetStartedAt(v time.Time) *DesktopConversationRecordCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetStoppedAt sets the "stopped_at" field.
func (_c *DesktopConversationRecordCreate) SetStoppedAt(v time.Time) *DesktopConversationRecordCreate {
	_c.mutation.SetStoppedAt(v)
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *DesktopConversationRecordCreate) SetReceivedAt(v time.Time) *DesktopConversationRecordCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *DesktopConversationRecordCreate) SetNillableReceivedAt(v *time.Time) *DesktopConversationRecordCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// SetCwd sets the "cwd" field.
func (_c *DesktopConversationRecordCreate) SetCwd(v string) *DesktopConversationRecordCreate {
	_c.mutation.SetCwd(v)
	return _c
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_c *DesktopConversationRecordCreate) SetNillableCwd(v *string) *DesktopConversationRecordCreate {
	if v != nil {
		_c.SetCwd(*v)
	}
	return _c
}

// SetPrompts sets the "prompts" field.
func (_c *DesktopConversationRecordCreate) SetPrompts(v jsontext.Value) *DesktopConversationRecordCreate {
	_c.mutation.SetPrompts(v)
	return _c
}

// SetResponse sets the "response" field.
func (_c *DesktopConversationRecordCreate) SetResponse(v jsontext.Value) *DesktopConversationRecordCreate {
	_c.mutation.SetResponse(v)
	return _c
}

// SetCaptureStatus sets the "capture_status" field.
func (_c *DesktopConversationRecordCreate) SetCaptureStatus(v string) *DesktopConversationRecordCreate {
	_c.mutation.SetCaptureStatus(v)
	return _c
}

// SetPromptCount sets the "prompt_count" field.
func (_c *DesktopConversationRecordCreate) SetPromptCount(v int) *DesktopConversationRecordCreate {
	_c.mutation.SetPromptCount(v)
	return _c
}

// SetOrganization sets the "organization" edge to the DesktopOrganization entity.
func (_c *DesktopConversationRecordCreate) SetOrganization(v *DesktopOrganization) *DesktopConversationRecordCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetMember sets the "member" edge to the DesktopMember entity.
func (_c *DesktopConversationRecordCreate) SetMember(v *DesktopMember) *DesktopConversationRecordCreate {
	return _c.SetMemberID(v.ID)
}

// Mutation returns the DesktopConversationRecordMutation object of the builder.
func (_c *DesktopConversationRecordCreate) Mutation() *DesktopConversationRecordMutation {
	return _c.mutation
}

// Save creates the DesktopConversationRecord in the database.
func (_c *DesktopConversationRecordCreate) Save(ctx context.Context) (*DesktopConversationRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopConversationRecordCreate) SaveX(ctx context.Context) *DesktopConversationRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopConversationRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopConversationRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopConversationRecordCreate) defaults() {
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		v := desktopconversationrecord.DefaultReceivedAt()
		_c.mutation.SetReceivedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopConversationRecordCreate) check() error {
	if _, ok := _c.mutation.RecordID(); !ok {
		return &ValidationError{Name: "record_id", err: errors.New(`ent: missing required field "DesktopConversationRecord.record_id"`)}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "DesktopConversationRecord.organization_id"`)}
	}
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "DesktopConversationRecord.member_id"`)}
	}
	if _, ok := _c.mutation.InstallationID(); !ok {
		return &ValidationError{Name: "installation_id", err: errors.New(`ent: missing required field "DesktopConversationRecord.installation_id"`)}
	}
	if _, ok := _c.mutation.GetClient(); !ok {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required field "DesktopConversationRecord.client"`)}
	}
	if v, ok := _c.mutation.GetClient(); ok {
		if err := desktopconversationrecord.ClientValidator(v); err != nil {
			return &ValidationError{Name: "client", err: fmt.Errorf(`ent: validator failed for field "DesktopConversationRecord.client": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceSessionID(); !ok {
		return &ValidationError{Name: "source_session_id", err: errors.New(`ent: missing required field "DesktopConversationRecord.source_session_id"`)}
	}
	if v, ok := _c.mutation.SourceSessionID(); ok {
		if err := desktopconversationrecord.SourceSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "source_session_id", err: fmt.Errorf(`ent: validator failed for field "DesktopConversationRecord.source_session_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceTurnID(); ok {
		if err := desktopconversationrecord.SourceTurnIDValidator(v); err != nil {
			return &ValidationError{Name: "source_turn_id", err: fmt.Errorf(`ent: validator failed for field "DesktopConversationRecord.source_turn_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "DesktopConversationRecord.started_at"`)}
	}
	if _, ok := _c.mutation.StoppedAt(); !ok {
		return &ValidationError{Name: "stopped_at", err: errors.New(`ent: missing required field "DesktopConversationRecord.stopped_at"`)}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "DesktopConversationRecord.received_at"`)}
	}
	if _, ok := _c.mutation.Prompts(); !ok {
		return &ValidationError{Name: "prompts", err: errors.New(`ent: missing required field "DesktopConversationRecord.prompts"`)}
	}
	if _, ok := _c.mutation.CaptureStatus(); !ok {
		return &ValidationError{Name: "capture_status", err: errors.New(`ent: missing required field "DesktopConversationRecord.capture_status"`)}
	}
	if v, ok := _c.mutation.CaptureStatus(); ok {
		if err := desktopconversationrecord.CaptureStatusValidator(v); err != nil {
			return &ValidationError{Name: "capture_status", err: fmt.Errorf(`ent: validator failed for field "DesktopConversationRecord.capture_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromptCount(); !ok {
		return &ValidationError{Name: "prompt_count", err: errors.New(`ent: missing required field "DesktopConversationRecord.prompt_count"`)}
	}
	if v, ok := _c.mutation.PromptCount(); ok {
		if err := desktopconversationrecord.PromptCountValidator(v); err != nil {
			return &ValidationError{Name: "prompt_count", err: fmt.Errorf(`ent: validator failed for field "DesktopConversationRecord.prompt_count": %w`, err)}
		}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "DesktopConversationRecord.organization"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "DesktopConversationRecord.member"`)}
	}
	return nil
}

func (_c *DesktopConversationRecordCreate) sqlSave(ctx context.Context) (*DesktopConversationRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopConversationRecordCreate) createSpec() (*DesktopConversationRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopConversationRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktopconversationrecord.Table, sqlgraph.NewFieldSpec(desktopconversationrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RecordID(); ok {
		_spec.SetField(desktopconversationrecord.FieldRecordID, field.TypeUUID, value)
		_node.RecordID = value
	}
	if value, ok := _c.mutation.InstallationID(); ok {
		_spec.SetField(desktopconversationrecord.FieldInstallationID, field.TypeUUID, value)
		_node.InstallationID = value
	}
	if value, ok := _c.mutation.GetClient(); ok {
		_spec.SetField(desktopconversationrecord.FieldClient, field.TypeString, value)
		_node.Client = value
	}
	if value, ok := _c.mutation.SourceSessionID(); ok {
		_spec.SetField(desktopconversationrecord.FieldSourceSessionID, field.TypeString, value)
		_node.SourceSessionID = value
	}
	if value, ok := _c.mutation.SourceTurnID(); ok {
		_spec.SetField(desktopconversationrecord.FieldSourceTurnID, field.TypeString, value)
		_node.SourceTurnID = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(desktopconversationrecord.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.StoppedAt(); ok {
		_spec.SetField(desktopconversationrecord.FieldStoppedAt, field.TypeTime, value)
		_node.StoppedAt = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(desktopconversationrecord.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.Cwd(); ok {
		_spec.SetField(desktopconversationrecord.FieldCwd, field.TypeString, value)
		_node.Cwd = &value
	}
	if value, ok := _c.mutation.Prompts(); ok {
		_spec.SetField(desktopconversationrecord.FieldPrompts, field.TypeJSON, value)
		_node.Prompts = value
	}
	if value, ok := _c.mutation.Response(); ok {
		_spec.SetField(desktopconversationrecord.FieldResponse, field.TypeJSON, value)
		_node.Response = value
	}
	if value, ok := _c.mutation.CaptureStatus(); ok {
		_spec.SetField(desktopconversationrecord.FieldCaptureStatus, field.TypeString, value)
		_node.CaptureStatus = value
	}
	if value, ok := _c.mutation.PromptCount(); ok {
		_spec.SetField(desktopconversationrecord.FieldPromptCount, field.TypeInt, value)
		_node.PromptCount = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   desktopconversationrecord.OrganizationTable,
			Columns: []string{desktopconversationrecord.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   desktopconversationrecord.MemberTable,
			Columns: []string{desktopconversationrecord.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopConversationRecord.Create().
//		SetRecordID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopConversationRecordUpsert) {
//			SetRecordID(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopConversationRecordCreate) OnConflict(opts ...sql.ConflictOption) *DesktopConversationRecordUpsertOne {
	_c.conflict = opts
	return &DesktopConversationRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopConversationRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopConversationRecordCreate) OnConflictColumns(columns ...string) *DesktopConversationRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopConversationRecordUpsertOne{
		create: _c,
	}
}

type (
	// DesktopConversationRecordUpsertOne is the builder for "upsert"-ing
	//  one DesktopConversationRecord node.
	DesktopConversationRecordUpsertOne struct {
		create *DesktopConversationRecordCreate
	}

	// DesktopConversationRecordUpsert is the "OnConflict" setter.
	DesktopConversationRecordUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopConversationRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopConversationRecordUpsertOne) UpdateNewValues() *DesktopConversationRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.RecordID(); exists {
			s.SetIgnore(desktopconversationrecord.FieldRecordID)
		}
		if _, exists := u.create.mutation.OrganizationID(); exists {
			s.SetIgnore(desktopconversationrecord.FieldOrganizationID)
		}
		if _, exists := u.create.mutation.MemberID(); exists {
			s.SetIgnore(desktopconversationrecord.FieldMemberID)
		}
		if _, exists := u.create.mutation.InstallationID(); exists {
			s.SetIgnore(desktopconversationrecord.FieldInstallationID)
		}
		if _, exists := u.create.mutation.GetClient(); exists {
			s.SetIgnore(desktopconversationrecord.FieldClient)
		}
		if _, exists := u.create.mutation.SourceSessionID(); exists {
			s.SetIgnore(desktopconversationrecord.FieldSourceSessionID)
		}
		if _, exists := u.create.mutation.SourceTurnID(); exists {
			s.SetIgnore(desktopconversationrecord.FieldSourceTurnID)
		}
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(desktopconversationrecord.FieldStartedAt)
		}
		if _, exists := u.create.mutation.StoppedAt(); exists {
			s.SetIgnore(desktopconversationrecord.FieldStoppedAt)
		}
		if _, exists := u.create.mutation.ReceivedAt(); exists {
			s.SetIgnore(desktopconversationrecord.FieldReceivedAt)
		}
		if _, exists := u.create.mutation.Cwd(); exists {
			s.SetIgnore(desktopconversationrecord.FieldCwd)
		}
		if _, exists := u.create.mutation.Prompts(); exists {
			s.SetIgnore(desktopconversationrecord.FieldPrompts)
		}
		if _, exists := u.create.mutation.Response(); exists {
			s.SetIgnore(desktopconversationrecord.FieldResponse)
		}
		if _, exists := u.create.mutation.CaptureStatus(); exists {
			s.SetIgnore(desktopconversationrecord.FieldCaptureStatus)
		}
		if _, exists := u.create.mutation.PromptCount(); exists {
			s.SetIgnore(desktopconversationrecord.FieldPromptCount)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopConversationRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopConversationRecordUpsertOne) Ignore() *DesktopConversationRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopConversationRecordUpsertOne) DoNothing() *DesktopConversationRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopConversationRecordCreate.OnConflict
// documentation for more info.
func (u *DesktopConversationRecordUpsertOne) Update(set func(*DesktopConversationRecordUpsert)) *DesktopConversationRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopConversationRecordUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *DesktopConversationRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopConversationRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopConversationRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopConversationRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopConversationRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopConversationRecordCreateBulk is the builder for creating many DesktopConversationRecord entities in bulk.
type DesktopConversationRecordCreateBulk struct {
	config
	err      error
	builders []*DesktopConversationRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopConversationRecord entities in the database.
func (_c *DesktopConversationRecordCreateBulk) Save(ctx context.Context) ([]*DesktopConversationRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopConversationRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopConversationRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopConversationRecordCreateBulk) SaveX(ctx context.Context) []*DesktopConversationRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopConversationRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopConversationRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopConversationRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopConversationRecordUpsert) {
//			SetRecordID(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopConversationRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopConversationRecordUpsertBulk {
	_c.conflict = opts
	return &DesktopConversationRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopConversationRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopConversationRecordCreateBulk) OnConflictColumns(columns ...string) *DesktopConversationRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopConversationRecordUpsertBulk{
		create: _c,
	}
}

// DesktopConversationRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopConversationRecord nodes.
type DesktopConversationRecordUpsertBulk struct {
	create *DesktopConversationRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopConversationRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopConversationRecordUpsertBulk) UpdateNewValues() *DesktopConversationRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.RecordID(); exists {
				s.SetIgnore(desktopconversationrecord.FieldRecordID)
			}
			if _, exists := b.mutation.OrganizationID(); exists {
				s.SetIgnore(desktopconversationrecord.FieldOrganizationID)
			}
			if _, exists := b.mutation.MemberID(); exists {
				s.SetIgnore(desktopconversationrecord.FieldMemberID)
			}
			if _, exists := b.mutation.InstallationID(); exists {
				s.SetIgnore(desktopconversationrecord.FieldInstallationID)
			}
			if _, exists := b.mutation.GetClient(); exists {
				s.SetIgnore(desktopconversationrecord.FieldClient)
			}
			if _, exists := b.mutation.SourceSessionID(); exists {
				s.SetIgnore(desktopconversationrecord.FieldSourceSessionID)
			}
			if _, exists := b.mutation.SourceTurnID(); exists {
				s.SetIgnore(desktopconversationrecord.FieldSourceTurnID)
			}
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(desktopconversationrecord.FieldStartedAt)
			}
			if _, exists := b.mutation.StoppedAt(); exists {
				s.SetIgnore(desktopconversationrecord.FieldStoppedAt)
			}
			if _, exists := b.mutation.ReceivedAt(); exists {
				s.SetIgnore(desktopconversationrecord.FieldReceivedAt)
			}
			if _, exists := b.mutation.Cwd(); exists {
				s.SetIgnore(desktopconversationrecord.FieldCwd)
			}
			if _, exists := b.mutation.Prompts(); exists {
				s.SetIgnore(desktopconversationrecord.FieldPrompts)
			}
			if _, exists := b.mutation.Response(); exists {
				s.SetIgnore(desktopconversationrecord.FieldResponse)
			}
			if _, exists := b.mutation.CaptureStatus(); exists {
				s.SetIgnore(desktopconversationrecord.FieldCaptureStatus)
			}
			if _, exists := b.mutation.PromptCount(); exists {
				s.SetIgnore(desktopconversationrecord.FieldPromptCount)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopConversationRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopConversationRecordUpsertBulk) Ignore() *DesktopConversationRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopConversationRecordUpsertBulk) DoNothing() *DesktopConversationRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopConversationRecordCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopConversationRecordUpsertBulk) Update(set func(*DesktopConversationRecordUpsert)) *DesktopConversationRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopConversationRecordUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *DesktopConversationRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopConversationRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopConversationRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopConversationRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
