// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktopmemberapikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopMemberAPIKeyUpdate is the builder for updating DesktopMemberAPIKey entities.
type DesktopMemberAPIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopMemberAPIKeyMutation
}

// Where appends a list predicates to the DesktopMemberAPIKeyUpdate builder.
func (_u *DesktopMemberAPIKeyUpdate) Where(ps ...predicate.DesktopMemberAPIKey) *DesktopMemberAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *DesktopMemberAPIKeyUpdate) SetMemberID(v int64) *DesktopMemberAPIKeyUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *DesktopMemberAPIKeyUpdate) SetNillableMemberID(v *int64) *DesktopMemberAPIKeyUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *DesktopMemberAPIKeyUpdate) SetAPIKeyID(v int64) *DesktopMemberAPIKeyUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *DesktopMemberAPIKeyUpdate) SetNillableAPIKeyID(v *int64) *DesktopMemberAPIKeyUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRetiredAt sets the "retired_at" field.
func (_u *DesktopMemberAPIKeyUpdate) SetRetiredAt(v time.Time) *DesktopMemberAPIKeyUpdate {
	_u.mutation.SetRetiredAt(v)
	return _u
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_u *DesktopMemberAPIKeyUpdate) SetNillableRetiredAt(v *time.Time) *DesktopMemberAPIKeyUpdate {
	if v != nil {
		_u.SetRetiredAt(*v)
	}
	return _u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (_u *DesktopMemberAPIKeyUpdate) ClearRetiredAt() *DesktopMemberAPIKeyUpdate {
	_u.mutation.ClearRetiredAt()
	return _u
}

// SetMember sets the "member" edge to the DesktopMember entity.
func (_u *DesktopMemberAPIKeyUpdate) SetMember(v *DesktopMember) *DesktopMemberAPIKeyUpdate {
	return _u.SetMemberID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *DesktopMemberAPIKeyUpdate) SetAPIKey(v *APIKey) *DesktopMemberAPIKeyUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the DesktopMemberAPIKeyMutation object of the builder.
func (_u *DesktopMemberAPIKeyUpdate) Mutation() *DesktopMemberAPIKeyMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the DesktopMember entity.
func (_u *DesktopMemberAPIKeyUpdate) ClearMember() *DesktopMemberAPIKeyUpdate {
	_u.mutation.ClearMember()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *DesktopMemberAPIKeyUpdate) ClearAPIKey() *DesktopMemberAPIKeyUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopMemberAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopMemberAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopMemberAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopMemberAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopMemberAPIKeyUpdate) check() error {
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopMemberAPIKey.member"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopMemberAPIKey.api_key"`)
	}
	return nil
}

func (_u *DesktopMemberAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopmemberapikey.Table, desktopmemberapikey.Columns, sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RetiredAt(); ok {
		_spec.SetField(desktopmemberapikey.FieldRetiredAt, field.TypeTime, value)
	}
	if _u.mutation.RetiredAtCleared() {
		_spec.ClearField(desktopmemberapikey.FieldRetiredAt, field.TypeTime)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmemberapikey.MemberTable,
			Columns: []string{desktopmemberapikey.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmemberapikey.MemberTable,
			Columns: []string{desktopmemberapikey.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   desktopmemberapikey.APIKeyTable,
			Columns: []string{desktopmemberapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   desktopmemberapikey.APIKeyTable,
			Columns: []string{desktopmemberapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopmemberapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopMemberAPIKeyUpdateOne is the builder for updating a single DesktopMemberAPIKey entity.
type DesktopMemberAPIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopMemberAPIKeyMutation
}

// SetMemberID sets the "member_id" field.
func (_u *DesktopMemberAPIKeyUpdateOne) SetMemberID(v int64) *DesktopMemberAPIKeyUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *DesktopMemberAPIKeyUpdateOne) SetNillableMemberID(v *int64) *DesktopMemberAPIKeyUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *DesktopMemberAPIKeyUpdateOne) SetAPIKeyID(v int64) *DesktopMemberAPIKeyUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *DesktopMemberAPIKeyUpdateOne) SetNillableAPIKeyID(v *int64) *DesktopMemberAPIKeyUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRetiredAt sets the "retired_at" field.
func (_u *DesktopMemberAPIKeyUpdateOne) SetRetiredAt(v time.Time) *DesktopMemberAPIKeyUpdateOne {
	_u.mutation.SetRetiredAt(v)
	return _u
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_u *DesktopMemberAPIKeyUpdateOne) SetNillableRetiredAt(v *time.Time) *DesktopMemberAPIKeyUpdateOne {
	if v != nil {
		_u.SetRetiredAt(*v)
	}
	return _u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (_u *DesktopMemberAPIKeyUpdateOne) ClearRetiredAt() *DesktopMemberAPIKeyUpdateOne {
	_u.mutation.ClearRetiredAt()
	return _u
}

// SetMember sets the "member" edge to the DesktopMember entity.
func (_u *DesktopMemberAPIKeyUpdateOne) SetMember(v *DesktopMember) *DesktopMemberAPIKeyUpdateOne {
	return _u.SetMemberID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *DesktopMemberAPIKeyUpdateOne) SetAPIKey(v *APIKey) *DesktopMemberAPIKeyUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the DesktopMemberAPIKeyMutation object of the builder.
func (_u *DesktopMemberAPIKeyUpdateOne) Mutation() *DesktopMemberAPIKeyMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the DesktopMember entity.
func (_u *DesktopMemberAPIKeyUpdateOne) ClearMember() *DesktopMemberAPIKeyUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *DesktopMemberAPIKeyUpdateOne) ClearAPIKey() *DesktopMemberAPIKeyUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the DesktopMemberAPIKeyUpdate builder.
func (_u *DesktopMemberAPIKeyUpdateOne) Where(ps ...predicate.DesktopMemberAPIKey) *DesktopMemberAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopMemberAPIKeyUpdateOne) Select(field string, fields ...string) *DesktopMemberAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopMemberAPIKey entity.
func (_u *DesktopMemberAPIKeyUpdateOne) Save(ctx context.Context) (*DesktopMemberAPIKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopMemberAPIKeyUpdateOne) SaveX(ctx context.Context) *DesktopMemberAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopMemberAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopMemberAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopMemberAPIKeyUpdateOne) check() error {
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopMemberAPIKey.member"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopMemberAPIKey.api_key"`)
	}
	return nil
}

func (_u *DesktopMemberAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *DesktopMemberAPIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopmemberapikey.Table, desktopmemberapikey.Columns, sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopMemberAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopmemberapikey.FieldID)
		for _, f := range fields {
			if !desktopmemberapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopmemberapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RetiredAt(); ok {
		_spec.SetField(desktopmemberapikey.FieldRetiredAt, field.TypeTime, value)
	}
	if _u.mutation.RetiredAtCleared() {
		_spec.ClearField(desktopmemberapikey.FieldRetiredAt, field.TypeTime)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmemberapikey.MemberTable,
			Columns: []string{desktopmemberapikey.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmemberapikey.MemberTable,
			Columns: []string{desktopmemberapikey.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   desktopmemberapikey.APIKeyTable,
			Columns: []string{desktopmemberapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   desktopmemberapikey.APIKeyTable,
			Columns: []string{desktopmemberapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DesktopMemberAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopmemberapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
