// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktopmemberapikey"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopMemberUpdate is the builder for updating DesktopMember entities.
type DesktopMemberUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopMemberMutation
}

// Where appends a list predicates to the DesktopMemberUpdate builder.
func (_u *DesktopMemberUpdate) Where(ps ...predicate.DesktopMember) *DesktopMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopMemberUpdate) SetUpdatedAt(v time.Time) *DesktopMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DesktopMemberUpdate) SetDeletedAt(v time.Time) *DesktopMemberUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillableDeletedAt(v *time.Time) *DesktopMemberUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DesktopMemberUpdate) ClearDeletedAt() *DesktopMemberUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *DesktopMemberUpdate) SetOrganizationID(v int64) *DesktopMemberUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillableOrganizationID(v *int64) *DesktopMemberUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DesktopMemberUpdate) SetName(v string) *DesktopMemberUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillableName(v *string) *DesktopMemberUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameNormalized sets the "name_normalized" field.
func (_u *DesktopMemberUpdate) SetNameNormalized(v string) *DesktopMemberUpdate {
	_u.mutation.SetNameNormalized(v)
	return _u
}

// SetNillableNameNormalized sets the "name_normalized" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillableNameNormalized(v *string) *DesktopMemberUpdate {
	if v != nil {
		_u.SetNameNormalized(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *DesktopMemberUpdate) SetPhone(v string) *DesktopMemberUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillablePhone(v *string) *DesktopMemberUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopMemberUpdate) SetStatus(v string) *DesktopMemberUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillableStatus(v *string) *DesktopMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthVersion sets the "auth_version" field.
func (_u *DesktopMemberUpdate) SetAuthVersion(v int64) *DesktopMemberUpdate {
	_u.mutation.ResetAuthVersion()
	_u.mutation.SetAuthVersion(v)
	return _u
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillableAuthVersion(v *int64) *DesktopMemberUpdate {
	if v != nil {
		_u.SetAuthVersion(*v)
	}
	return _u
}

// AddAuthVersion adds value to the "auth_version" field.
func (_u *DesktopMemberUpdate) AddAuthVersion(v int64) *DesktopMemberUpdate {
	_u.mutation.AddAuthVersion(v)
	return _u
}

// SetAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field.
func (_u *DesktopMemberUpdate) SetAPIKeySuspendedByOrganization(v bool) *DesktopMemberUpdate {
	_u.mutation.SetAPIKeySuspendedByOrganization(v)
	return _u
}

// SetNillableAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field if the given value is not nil.
func (_u *DesktopMemberUpdate) SetNillableAPIKeySuspendedByOrganization(v *bool) *DesktopMemberUpdate {
	if v != nil {
		_u.SetAPIKeySuspendedByOrganization(*v)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the DesktopOrganization entity.
func (_u *DesktopMemberUpdate) SetOrganization(v *DesktopOrganization) *DesktopMemberUpdate {
	return _u.SetOrganizationID(v.ID)
}

// AddAPIKeyAssignmentIDs adds the "api_key_assignments" edge to the DesktopMemberAPIKey entity by IDs.
func (_u *DesktopMemberUpdate) AddAPIKeyAssignmentIDs(ids ...int64) *DesktopMemberUpdate {
	_u.mutation.AddAPIKeyAssignmentIDs(ids...)
	return _u
}

// AddAPIKeyAssignments adds the "api_key_assignments" edges to the DesktopMemberAPIKey entity.
func (_u *DesktopMemberUpdate) AddAPIKeyAssignments(v ...*DesktopMemberAPIKey) *DesktopMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyAssignmentIDs(ids...)
}

// Mutation returns the DesktopMemberMutation object of the builder.
func (_u *DesktopMemberUpdate) Mutation() *DesktopMemberMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the DesktopOrganization entity.
func (_u *DesktopMemberUpdate) ClearOrganization() *DesktopMemberUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearAPIKeyAssignments clears all "api_key_assignments" edges to the DesktopMemberAPIKey entity.
func (_u *DesktopMemberUpdate) ClearAPIKeyAssignments() *DesktopMemberUpdate {
	_u.mutation.ClearAPIKeyAssignments()
	return _u
}

// RemoveAPIKeyAssignmentIDs removes the "api_key_assignments" edge to DesktopMemberAPIKey entities by IDs.
func (_u *DesktopMemberUpdate) RemoveAPIKeyAssignmentIDs(ids ...int64) *DesktopMemberUpdate {
	_u.mutation.RemoveAPIKeyAssignmentIDs(ids...)
	return _u
}

// RemoveAPIKeyAssignments removes "api_key_assignments" edges to DesktopMemberAPIKey entities.
func (_u *DesktopMemberUpdate) RemoveAPIKeyAssignments(v ...*DesktopMemberAPIKey) *DesktopMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyAssignmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopMemberUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopMemberUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if desktopmember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktopmember.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := desktopmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopMemberUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := desktopmember.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameNormalized(); ok {
		if err := desktopmember.NameNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "name_normalized", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.name_normalized": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := desktopmember.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktopmember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthVersion(); ok {
		if err := desktopmember.AuthVersionValidator(v); err != nil {
			return &ValidationError{Name: "auth_version", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.auth_version": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopMember.organization"`)
	}
	return nil
}

func (_u *DesktopMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopmember.Table, desktopmember.Columns, sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(desktopmember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(desktopmember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(desktopmember.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameNormalized(); ok {
		_spec.SetField(desktopmember.FieldNameNormalized, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(desktopmember.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopmember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthVersion(); ok {
		_spec.SetField(desktopmember.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthVersion(); ok {
		_spec.AddField(desktopmember.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeySuspendedByOrganization(); ok {
		_spec.SetField(desktopmember.FieldAPIKeySuspendedByOrganization, field.TypeBool, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmember.OrganizationTable,
			Columns: []string{desktopmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmember.OrganizationTable,
			Columns: []string{desktopmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopmember.APIKeyAssignmentsTable,
			Columns: []string{desktopmember.APIKeyAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeyAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.APIKeyAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopmember.APIKeyAssignmentsTable,
			Columns: []string{desktopmember.APIKeyAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopmember.APIKeyAssignmentsTable,
			Columns: []string{desktopmember.APIKeyAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopMemberUpdateOne is the builder for updating a single DesktopMember entity.
type DesktopMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopMemberMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopMemberUpdateOne) SetUpdatedAt(v time.Time) *DesktopMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DesktopMemberUpdateOne) SetDeletedAt(v time.Time) *DesktopMemberUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillableDeletedAt(v *time.Time) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DesktopMemberUpdateOne) ClearDeletedAt() *DesktopMemberUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *DesktopMemberUpdateOne) SetOrganizationID(v int64) *DesktopMemberUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillableOrganizationID(v *int64) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DesktopMemberUpdateOne) SetName(v string) *DesktopMemberUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillableName(v *string) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameNormalized sets the "name_normalized" field.
func (_u *DesktopMemberUpdateOne) SetNameNormalized(v string) *DesktopMemberUpdateOne {
	_u.mutation.SetNameNormalized(v)
	return _u
}

// SetNillableNameNormalized sets the "name_normalized" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillableNameNormalized(v *string) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetNameNormalized(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *DesktopMemberUpdateOne) SetPhone(v string) *DesktopMemberUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillablePhone(v *string) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopMemberUpdateOne) SetStatus(v string) *DesktopMemberUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillableStatus(v *string) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthVersion sets the "auth_version" field.
func (_u *DesktopMemberUpdateOne) SetAuthVersion(v int64) *DesktopMemberUpdateOne {
	_u.mutation.ResetAuthVersion()
	_u.mutation.SetAuthVersion(v)
	return _u
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillableAuthVersion(v *int64) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetAuthVersion(*v)
	}
	return _u
}

// AddAuthVersion adds value to the "auth_version" field.
func (_u *DesktopMemberUpdateOne) AddAuthVersion(v int64) *DesktopMemberUpdateOne {
	_u.mutation.AddAuthVersion(v)
	return _u
}

// SetAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field.
func (_u *DesktopMemberUpdateOne) SetAPIKeySuspendedByOrganization(v bool) *DesktopMemberUpdateOne {
	_u.mutation.SetAPIKeySuspendedByOrganization(v)
	return _u
}

// SetNillableAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field if the given value is not nil.
func (_u *DesktopMemberUpdateOne) SetNillableAPIKeySuspendedByOrganization(v *bool) *DesktopMemberUpdateOne {
	if v != nil {
		_u.SetAPIKeySuspendedByOrganization(*v)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the DesktopOrganization entity.
func (_u *DesktopMemberUpdateOne) SetOrganization(v *DesktopOrganization) *DesktopMemberUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// AddAPIKeyAssignmentIDs adds the "api_key_assignments" edge to the DesktopMemberAPIKey entity by IDs.
func (_u *DesktopMemberUpdateOne) AddAPIKeyAssignmentIDs(ids ...int64) *DesktopMemberUpdateOne {
	_u.mutation.AddAPIKeyAssignmentIDs(ids...)
	return _u
}

// AddAPIKeyAssignments adds the "api_key_assignments" edges to the DesktopMemberAPIKey entity.
func (_u *DesktopMemberUpdateOne) AddAPIKeyAssignments(v ...*DesktopMemberAPIKey) *DesktopMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyAssignmentIDs(ids...)
}

// Mutation returns the DesktopMemberMutation object of the builder.
func (_u *DesktopMemberUpdateOne) Mutation() *DesktopMemberMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the DesktopOrganization entity.
func (_u *DesktopMemberUpdateOne) ClearOrganization() *DesktopMemberUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearAPIKeyAssignments clears all "api_key_assignments" edges to the DesktopMemberAPIKey entity.
func (_u *DesktopMemberUpdateOne) ClearAPIKeyAssignments() *DesktopMemberUpdateOne {
	_u.mutation.ClearAPIKeyAssignments()
	return _u
}

// RemoveAPIKeyAssignmentIDs removes the "api_key_assignments" edge to DesktopMemberAPIKey entities by IDs.
func (_u *DesktopMemberUpdateOne) RemoveAPIKeyAssignmentIDs(ids ...int64) *DesktopMemberUpdateOne {
	_u.mutation.RemoveAPIKeyAssignmentIDs(ids...)
	return _u
}

// RemoveAPIKeyAssignments removes "api_key_assignments" edges to DesktopMemberAPIKey entities.
func (_u *DesktopMemberUpdateOne) RemoveAPIKeyAssignments(v ...*DesktopMemberAPIKey) *DesktopMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyAssignmentIDs(ids...)
}

// Where appends a list predicates to the DesktopMemberUpdate builder.
func (_u *DesktopMemberUpdateOne) Where(ps ...predicate.DesktopMember) *DesktopMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopMemberUpdateOne) Select(field string, fields ...string) *DesktopMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopMember entity.
func (_u *DesktopMemberUpdateOne) Save(ctx context.Context) (*DesktopMember, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopMemberUpdateOne) SaveX(ctx context.Context) *DesktopMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopMemberUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if desktopmember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktopmember.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := desktopmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopMemberUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := desktopmember.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameNormalized(); ok {
		if err := desktopmember.NameNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "name_normalized", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.name_normalized": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := desktopmember.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktopmember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthVersion(); ok {
		if err := desktopmember.AuthVersionValidator(v); err != nil {
			return &ValidationError{Name: "auth_version", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.auth_version": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopMember.organization"`)
	}
	return nil
}

func (_u *DesktopMemberUpdateOne) sqlSave(ctx context.Context) (_node *DesktopMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopmember.Table, desktopmember.Columns, sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopmember.FieldID)
		for _, f := range fields {
			if !desktopmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(desktopmember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(desktopmember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(desktopmember.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameNormalized(); ok {
		_spec.SetField(desktopmember.FieldNameNormalized, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(desktopmember.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopmember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthVersion(); ok {
		_spec.SetField(desktopmember.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthVersion(); ok {
		_spec.AddField(desktopmember.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeySuspendedByOrganization(); ok {
		_spec.SetField(desktopmember.FieldAPIKeySuspendedByOrganization, field.TypeBool, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmember.OrganizationTable,
			Columns: []string{desktopmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmember.OrganizationTable,
			Columns: []string{desktopmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopmember.APIKeyAssignmentsTable,
			Columns: []string{desktopmember.APIKeyAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeyAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.APIKeyAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopmember.APIKeyAssignmentsTable,
			Columns: []string{desktopmember.APIKeyAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopmember.APIKeyAssignmentsTable,
			Columns: []string{desktopmember.APIKeyAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DesktopMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
