// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopOrganization is the model entity for the DesktopOrganization schema.
type DesktopOrganization struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AuthVersion holds the value of the "auth_version" field.
	AuthVersion int64 `json:"auth_version,omitempty"`
	// GatewayUserID holds the value of the "gateway_user_id" field.
	GatewayUserID int64 `json:"gateway_user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// TargetConfig holds the value of the "target_config" field.
	TargetConfig jsontext.Value `json:"target_config,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DesktopOrganizationQuery when eager-loading is set.
	Edges        DesktopOrganizationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DesktopOrganizationEdges holds the relations/edges for other nodes in the graph.
type DesktopOrganizationEdges struct {
	// GatewayUser holds the value of the gateway_user edge.
	GatewayUser *User `json:"gateway_user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Members holds the value of the members edge.
	Members []*DesktopMember `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GatewayUserOrErr returns the GatewayUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopOrganizationEdges) GatewayUserOrErr() (*User, error) {
	if e.GatewayUser != nil {
		return e.GatewayUser, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "gateway_user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopOrganizationEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e DesktopOrganizationEdges) MembersOrErr() ([]*DesktopMember, error) {
	if e.loadedTypes[2] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DesktopOrganization) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case desktoporganization.FieldTargetConfig:
			values[i] = new([]byte)
		case desktoporganization.FieldID, desktoporganization.FieldAuthVersion, desktoporganization.FieldGatewayUserID, desktoporganization.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case desktoporganization.FieldPublicID, desktoporganization.FieldCode, desktoporganization.FieldName, desktoporganization.FieldStatus:
			values[i] = new(sql.NullString)
		case desktoporganization.FieldCreatedAt, desktoporganization.FieldUpdatedAt, desktoporganization.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DesktopOrganization fields.
func (_m *DesktopOrganization) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case desktoporganization.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case desktoporganization.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case desktoporganization.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case desktoporganization.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case desktoporganization.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case desktoporganization.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case desktoporganization.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case desktoporganization.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case desktoporganization.FieldAuthVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auth_version", values[i])
			} else if value.Valid {
				_m.AuthVersion = value.Int64
			}
		case desktoporganization.FieldGatewayUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_user_id", values[i])
			} else if value.Valid {
				_m.GatewayUserID = value.Int64
			}
		case desktoporganization.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case desktoporganization.FieldTargetConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field target_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TargetConfig); err != nil {
					return fmt.Errorf("unmarshal field target_config: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DesktopOrganization.
// This includes values selected through modifiers, order, etc.
func (_m *DesktopOrganization) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGatewayUser queries the "gateway_user" edge of the DesktopOrganization entity.
func (_m *DesktopOrganization) QueryGatewayUser() *UserQuery {
	return NewDesktopOrganizationClient(_m.config).QueryGatewayUser(_m)
}

// QueryGroup queries the "group" edge of the DesktopOrganization entity.
func (_m *DesktopOrganization) QueryGroup() *GroupQuery {
	return NewDesktopOrganizationClient(_m.config).QueryGroup(_m)
}

// QueryMembers queries the "members" edge of the DesktopOrganization entity.
func (_m *DesktopOrganization) QueryMembers() *DesktopMemberQuery {
	return NewDesktopOrganizationClient(_m.config).QueryMembers(_m)
}

// Update returns a builder for updating this DesktopOrganization.
// Note that you need to call DesktopOrganization.Unwrap() before calling this method if this DesktopOrganization
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DesktopOrganization) Update() *DesktopOrganizationUpdateOne {
	return NewDesktopOrganizationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DesktopOrganization entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DesktopOrganization) Unwrap() *DesktopOrganization {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DesktopOrganization is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DesktopOrganization) String() string {
	var builder strings.Builder
	builder.WriteString("DesktopOrganization(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("auth_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthVersion))
	builder.WriteString(", ")
	builder.WriteString("gateway_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GatewayUserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("target_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetConfig))
	builder.WriteByte(')')
	return builder.String()
}

// DesktopOrganizations is a parsable slice of DesktopOrganization.
type DesktopOrganizations []*DesktopOrganization
