// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopOrganizationCreate is the builder for creating a DesktopOrganization entity.
type DesktopOrganizationCreate struct {
	config
	mutation *DesktopOrganizationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesktopOrganizationCreate) SetCreatedAt(v time.Time) *DesktopOrganizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesktopOrganizationCreate) SetNillableCreatedAt(v *time.Time) *DesktopOrganizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesktopOrganizationCreate) SetUpdatedAt(v time.Time) *DesktopOrganizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesktopOrganizationCreate) SetNillableUpdatedAt(v *time.Time) *DesktopOrganizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DesktopOrganizationCreate) SetDeletedAt(v time.Time) *DesktopOrganizationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DesktopOrganizationCreate) SetNillableDeletedAt(v *time.Time) *DesktopOrganizationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *DesktopOrganizationCreate) SetPublicID(v string) *DesktopOrganizationCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *DesktopOrganizationCreate) SetCode(v string) *DesktopOrganizationCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DesktopOrganizationCreate) SetName(v string) *DesktopOrganizationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DesktopOrganizationCreate) SetStatus(v string) *DesktopOrganizationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DesktopOrganizationCreate) SetNillableStatus(v *string) *DesktopOrganizationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAuthVersion sets the "auth_version" field.
func (_c *DesktopOrganizationCreate) SetAuthVersion(v int64) *DesktopOrganizationCreate {
	_c.mutation.SetAuthVersion(v)
	return _c
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_c *DesktopOrganizationCreate) SetNillableAuthVersion(v *int64) *DesktopOrganizationCreate {
	if v != nil {
		_c.SetAuthVersion(*v)
	}
	return _c
}

// SetGatewayUserID sets the "gateway_user_id" field.
func (_c *DesktopOrganizationCreate) SetGatewayUserID(v int64) *DesktopOrganizationCreate {
	_c.mutation.SetGatewayUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *DesktopOrganizationCreate) SetGroupID(v int64) *DesktopOrganizationCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetTargetConfig sets the "target_config" field.
func (_c *DesktopOrganizationCreate) SetTargetConfig(v jsontext.Value) *DesktopOrganizationCreate {
	_c.mutation.SetTargetConfig(v)
	return _c
}

// SetGatewayUser sets the "gateway_user" edge to the User entity.
func (_c *DesktopOrganizationCreate) SetGatewayUser(v *User) *DesktopOrganizationCreate {
	return _c.SetGatewayUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *DesktopOrganizationCreate) SetGroup(v *Group) *DesktopOrganizationCreate {
	return _c.SetGroupID(v.ID)
}

// AddMemberIDs adds the "members" edge to the DesktopMember entity by IDs.
func (_c *DesktopOrganizationCreate) AddMemberIDs(ids ...int64) *DesktopOrganizationCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the DesktopMember entity.
func (_c *DesktopOrganizationCreate) AddMembers(v ...*DesktopMember) *DesktopOrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// Mutation returns the DesktopOrganizationMutation object of the builder.
func (_c *DesktopOrganizationCreate) Mutation() *DesktopOrganizationMutation {
	return _c.mutation
}

// Save creates the DesktopOrganization in the database.
func (_c *DesktopOrganizationCreate) Save(ctx context.Context) (*DesktopOrganization, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopOrganizationCreate) SaveX(ctx context.Context) *DesktopOrganization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopOrganizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopOrganizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopOrganizationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if desktoporganization.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktoporganization.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := desktoporganization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if desktoporganization.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktoporganization.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := desktoporganization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := desktoporganization.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AuthVersion(); !ok {
		v := desktoporganization.DefaultAuthVersion
		_c.mutation.SetAuthVersion(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopOrganizationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DesktopOrganization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DesktopOrganization.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "DesktopOrganization.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := desktoporganization.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "DesktopOrganization.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := desktoporganization.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DesktopOrganization.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := desktoporganization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DesktopOrganization.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := desktoporganization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthVersion(); !ok {
		return &ValidationError{Name: "auth_version", err: errors.New(`ent: missing required field "DesktopOrganization.auth_version"`)}
	}
	if v, ok := _c.mutation.AuthVersion(); ok {
		if err := desktoporganization.AuthVersionValidator(v); err != nil {
			return &ValidationError{Name: "auth_version", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.auth_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GatewayUserID(); !ok {
		return &ValidationError{Name: "gateway_user_id", err: errors.New(`ent: missing required field "DesktopOrganization.gateway_user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "DesktopOrganization.group_id"`)}
	}
	if len(_c.mutation.GatewayUserIDs()) == 0 {
		return &ValidationError{Name: "gateway_user", err: errors.New(`ent: missing required edge "DesktopOrganization.gateway_user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "DesktopOrganization.group"`)}
	}
	return nil
}

func (_c *DesktopOrganizationCreate) sqlSave(ctx context.Context) (*DesktopOrganization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopOrganizationCreate) createSpec() (*DesktopOrganization, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopOrganization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktoporganization.Table, sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(desktoporganization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(desktoporganization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(desktoporganization.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(desktoporganization.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(desktoporganization.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(desktoporganization.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(desktoporganization.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AuthVersion(); ok {
		_spec.SetField(desktoporganization.FieldAuthVersion, field.TypeInt64, value)
		_node.AuthVersion = value
	}
	if value, ok := _c.mutation.TargetConfig(); ok {
		_spec.SetField(desktoporganization.FieldTargetConfig, field.TypeJSON, value)
		_node.TargetConfig = value
	}
	if nodes := _c.mutation.GatewayUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GatewayUserTable,
			Columns: []string{desktoporganization.GatewayUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GatewayUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GroupTable,
			Columns: []string{desktoporganization.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktoporganization.MembersTable,
			Columns: []string{desktoporganization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopOrganization.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopOrganizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopOrganizationCreate) OnConflict(opts ...sql.ConflictOption) *DesktopOrganizationUpsertOne {
	_c.conflict = opts
	return &DesktopOrganizationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopOrganization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopOrganizationCreate) OnConflictColumns(columns ...string) *DesktopOrganizationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopOrganizationUpsertOne{
		create: _c,
	}
}

type (
	// DesktopOrganizationUpsertOne is the builder for "upsert"-ing
	//  one DesktopOrganization node.
	DesktopOrganizationUpsertOne struct {
		create *DesktopOrganizationCreate
	}

	// DesktopOrganizationUpsert is the "OnConflict" setter.
	DesktopOrganizationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopOrganizationUpsert) SetUpdatedAt(v time.Time) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateUpdatedAt() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DesktopOrganizationUpsert) SetDeletedAt(v time.Time) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateDeletedAt() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DesktopOrganizationUpsert) ClearDeletedAt() *DesktopOrganizationUpsert {
	u.SetNull(desktoporganization.FieldDeletedAt)
	return u
}

// SetCode sets the "code" field.
func (u *DesktopOrganizationUpsert) SetCode(v string) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateCode() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *DesktopOrganizationUpsert) SetName(v string) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateName() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *DesktopOrganizationUpsert) SetStatus(v string) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateStatus() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldStatus)
	return u
}

// SetAuthVersion sets the "auth_version" field.
func (u *DesktopOrganizationUpsert) SetAuthVersion(v int64) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldAuthVersion, v)
	return u
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateAuthVersion() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldAuthVersion)
	return u
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *DesktopOrganizationUpsert) AddAuthVersion(v int64) *DesktopOrganizationUpsert {
	u.Add(desktoporganization.FieldAuthVersion, v)
	return u
}

// SetGatewayUserID sets the "gateway_user_id" field.
func (u *DesktopOrganizationUpsert) SetGatewayUserID(v int64) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldGatewayUserID, v)
	return u
}

// UpdateGatewayUserID sets the "gateway_user_id" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateGatewayUserID() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldGatewayUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *DesktopOrganizationUpsert) SetGroupID(v int64) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateGroupID() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldGroupID)
	return u
}

// SetTargetConfig sets the "target_config" field.
func (u *DesktopOrganizationUpsert) SetTargetConfig(v jsontext.Value) *DesktopOrganizationUpsert {
	u.Set(desktoporganization.FieldTargetConfig, v)
	return u
}

// UpdateTargetConfig sets the "target_config" field to the value that was provided on create.
func (u *DesktopOrganizationUpsert) UpdateTargetConfig() *DesktopOrganizationUpsert {
	u.SetExcluded(desktoporganization.FieldTargetConfig)
	return u
}

// ClearTargetConfig clears the value of the "target_config" field.
func (u *DesktopOrganizationUpsert) ClearTargetConfig() *DesktopOrganizationUpsert {
	u.SetNull(desktoporganization.FieldTargetConfig)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopOrganization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopOrganizationUpsertOne) UpdateNewValues() *DesktopOrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(desktoporganization.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.PublicID(); exists {
			s.SetIgnore(desktoporganization.FieldPublicID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopOrganization.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopOrganizationUpsertOne) Ignore() *DesktopOrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopOrganizationUpsertOne) DoNothing() *DesktopOrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopOrganizationCreate.OnConflict
// documentation for more info.
func (u *DesktopOrganizationUpsertOne) Update(set func(*DesktopOrganizationUpsert)) *DesktopOrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopOrganizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopOrganizationUpsertOne) SetUpdatedAt(v time.Time) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateUpdatedAt() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DesktopOrganizationUpsertOne) SetDeletedAt(v time.Time) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateDeletedAt() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DesktopOrganizationUpsertOne) ClearDeletedAt() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *DesktopOrganizationUpsertOne) SetCode(v string) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateCode() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *DesktopOrganizationUpsertOne) SetName(v string) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateName() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopOrganizationUpsertOne) SetStatus(v string) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateStatus() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *DesktopOrganizationUpsertOne) SetAuthVersion(v int64) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *DesktopOrganizationUpsertOne) AddAuthVersion(v int64) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateAuthVersion() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateAuthVersion()
	})
}

// SetGatewayUserID sets the "gateway_user_id" field.
func (u *DesktopOrganizationUpsertOne) SetGatewayUserID(v int64) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetGatewayUserID(v)
	})
}

// UpdateGatewayUserID sets the "gateway_user_id" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateGatewayUserID() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateGatewayUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DesktopOrganizationUpsertOne) SetGroupID(v int64) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateGroupID() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateGroupID()
	})
}

// SetTargetConfig sets the "target_config" field.
func (u *DesktopOrganizationUpsertOne) SetTargetConfig(v jsontext.Value) *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetTargetConfig(v)
	})
}

// UpdateTargetConfig sets the "target_config" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertOne) UpdateTargetConfig() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateTargetConfig()
	})
}

// ClearTargetConfig clears the value of the "target_config" field.
func (u *DesktopOrganizationUpsertOne) ClearTargetConfig() *DesktopOrganizationUpsertOne {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.ClearTargetConfig()
	})
}

// Exec executes the query.
func (u *DesktopOrganizationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopOrganizationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopOrganizationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopOrganizationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopOrganizationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopOrganizationCreateBulk is the builder for creating many DesktopOrganization entities in bulk.
type DesktopOrganizationCreateBulk struct {
	config
	err      error
	builders []*DesktopOrganizationCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopOrganization entities in the database.
func (_c *DesktopOrganizationCreateBulk) Save(ctx context.Context) ([]*DesktopOrganization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopOrganization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopOrganizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopOrganizationCreateBulk) SaveX(ctx context.Context) []*DesktopOrganization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopOrganizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopOrganizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopOrganization.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopOrganizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopOrganizationCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopOrganizationUpsertBulk {
	_c.conflict = opts
	return &DesktopOrganizationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopOrganization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopOrganizationCreateBulk) OnConflictColumns(columns ...string) *DesktopOrganizationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopOrganizationUpsertBulk{
		create: _c,
	}
}

// DesktopOrganizationUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopOrganization nodes.
type DesktopOrganizationUpsertBulk struct {
	create *DesktopOrganizationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopOrganization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopOrganizationUpsertBulk) UpdateNewValues() *DesktopOrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(desktoporganization.FieldCreatedAt)
			}
			if _, exists := b.mutation.PublicID(); exists {
				s.SetIgnore(desktoporganization.FieldPublicID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopOrganization.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopOrganizationUpsertBulk) Ignore() *DesktopOrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopOrganizationUpsertBulk) DoNothing() *DesktopOrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopOrganizationCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopOrganizationUpsertBulk) Update(set func(*DesktopOrganizationUpsert)) *DesktopOrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopOrganizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopOrganizationUpsertBulk) SetUpdatedAt(v time.Time) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateUpdatedAt() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DesktopOrganizationUpsertBulk) SetDeletedAt(v time.Time) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateDeletedAt() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DesktopOrganizationUpsertBulk) ClearDeletedAt() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *DesktopOrganizationUpsertBulk) SetCode(v string) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateCode() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *DesktopOrganizationUpsertBulk) SetName(v string) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateName() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopOrganizationUpsertBulk) SetStatus(v string) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateStatus() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *DesktopOrganizationUpsertBulk) SetAuthVersion(v int64) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *DesktopOrganizationUpsertBulk) AddAuthVersion(v int64) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateAuthVersion() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateAuthVersion()
	})
}

// SetGatewayUserID sets the "gateway_user_id" field.
func (u *DesktopOrganizationUpsertBulk) SetGatewayUserID(v int64) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetGatewayUserID(v)
	})
}

// UpdateGatewayUserID sets the "gateway_user_id" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateGatewayUserID() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateGatewayUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DesktopOrganizationUpsertBulk) SetGroupID(v int64) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateGroupID() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateGroupID()
	})
}

// SetTargetConfig sets the "target_config" field.
func (u *DesktopOrganizationUpsertBulk) SetTargetConfig(v jsontext.Value) *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.SetTargetConfig(v)
	})
}

// UpdateTargetConfig sets the "target_config" field to the value that was provided on create.
func (u *DesktopOrganizationUpsertBulk) UpdateTargetConfig() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.UpdateTargetConfig()
	})
}

// ClearTargetConfig clears the value of the "target_config" field.
func (u *DesktopOrganizationUpsertBulk) ClearTargetConfig() *DesktopOrganizationUpsertBulk {
	return u.Update(func(s *DesktopOrganizationUpsert) {
		s.ClearTargetConfig()
	})
}

// Exec executes the query.
func (u *DesktopOrganizationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopOrganizationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopOrganizationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopOrganizationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
