// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopupdaterelease"
)

// DesktopUpdateReleaseCreate is the builder for creating a DesktopUpdateRelease entity.
type DesktopUpdateReleaseCreate struct {
	config
	mutation *DesktopUpdateReleaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesktopUpdateReleaseCreate) SetCreatedAt(v time.Time) *DesktopUpdateReleaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableCreatedAt(v *time.Time) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesktopUpdateReleaseCreate) SetUpdatedAt(v time.Time) *DesktopUpdateReleaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableUpdatedAt(v *time.Time) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *DesktopUpdateReleaseCreate) SetPublicID(v string) *DesktopUpdateReleaseCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *DesktopUpdateReleaseCreate) SetVersion(v string) *DesktopUpdateReleaseCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *DesktopUpdateReleaseCreate) SetNotes(v string) *DesktopUpdateReleaseCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableNotes(v *string) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetArtifacts sets the "artifacts" field.
func (_c *DesktopUpdateReleaseCreate) SetArtifacts(v jsontext.Value) *DesktopUpdateReleaseCreate {
	_c.mutation.SetArtifacts(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DesktopUpdateReleaseCreate) SetStatus(v string) *DesktopUpdateReleaseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableStatus(v *string) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DesktopUpdateReleaseCreate) SetCreatedBy(v int64) *DesktopUpdateReleaseCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableCreatedBy(v *int64) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *DesktopUpdateReleaseCreate) SetUpdatedBy(v int64) *DesktopUpdateReleaseCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableUpdatedBy(v *int64) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetPublishedBy sets the "published_by" field.
func (_c *DesktopUpdateReleaseCreate) SetPublishedBy(v int64) *DesktopUpdateReleaseCreate {
	_c.mutation.SetPublishedBy(v)
	return _c
}

// SetNillablePublishedBy sets the "published_by" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillablePublishedBy(v *int64) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetPublishedBy(*v)
	}
	return _c
}

// SetWithdrawnBy sets the "withdrawn_by" field.
func (_c *DesktopUpdateReleaseCreate) SetWithdrawnBy(v int64) *DesktopUpdateReleaseCreate {
	_c.mutation.SetWithdrawnBy(v)
	return _c
}

// SetNillableWithdrawnBy sets the "withdrawn_by" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableWithdrawnBy(v *int64) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetWithdrawnBy(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *DesktopUpdateReleaseCreate) SetPublishedAt(v time.Time) *DesktopUpdateReleaseCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillablePublishedAt(v *time.Time) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetWithdrawnAt sets the "withdrawn_at" field.
func (_c *DesktopUpdateReleaseCreate) SetWithdrawnAt(v time.Time) *DesktopUpdateReleaseCreate {
	_c.mutation.SetWithdrawnAt(v)
	return _c
}

// SetNillableWithdrawnAt sets the "withdrawn_at" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableWithdrawnAt(v *time.Time) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetWithdrawnAt(*v)
	}
	return _c
}

// SetWithdrawalReason sets the "withdrawal_reason" field.
func (_c *DesktopUpdateReleaseCreate) SetWithdrawalReason(v string) *DesktopUpdateReleaseCreate {
	_c.mutation.SetWithdrawalReason(v)
	return _c
}

// SetNillableWithdrawalReason sets the "withdrawal_reason" field if the given value is not nil.
func (_c *DesktopUpdateReleaseCreate) SetNillableWithdrawalReason(v *string) *DesktopUpdateReleaseCreate {
	if v != nil {
		_c.SetWithdrawalReason(*v)
	}
	return _c
}

// Mutation returns the DesktopUpdateReleaseMutation object of the builder.
func (_c *DesktopUpdateReleaseCreate) Mutation() *DesktopUpdateReleaseMutation {
	return _c.mutation
}

// Save creates the DesktopUpdateRelease in the database.
func (_c *DesktopUpdateReleaseCreate) Save(ctx context.Context) (*DesktopUpdateRelease, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopUpdateReleaseCreate) SaveX(ctx context.Context) *DesktopUpdateRelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopUpdateReleaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopUpdateReleaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopUpdateReleaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := desktopupdaterelease.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := desktopupdaterelease.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := desktopupdaterelease.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := desktopupdaterelease.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopUpdateReleaseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DesktopUpdateRelease.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DesktopUpdateRelease.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "DesktopUpdateRelease.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := desktopupdaterelease.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "DesktopUpdateRelease.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "DesktopUpdateRelease.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := desktopupdaterelease.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DesktopUpdateRelease.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "DesktopUpdateRelease.notes"`)}
	}
	if _, ok := _c.mutation.Artifacts(); !ok {
		return &ValidationError{Name: "artifacts", err: errors.New(`ent: missing required field "DesktopUpdateRelease.artifacts"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DesktopUpdateRelease.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := desktopupdaterelease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopUpdateRelease.status": %w`, err)}
		}
	}
	return nil
}

func (_c *DesktopUpdateReleaseCreate) sqlSave(ctx context.Context) (*DesktopUpdateRelease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopUpdateReleaseCreate) createSpec() (*DesktopUpdateRelease, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopUpdateRelease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktopupdaterelease.Table, sqlgraph.NewFieldSpec(desktopupdaterelease.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(desktopupdaterelease.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopupdaterelease.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(desktopupdaterelease.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(desktopupdaterelease.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(desktopupdaterelease.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Artifacts(); ok {
		_spec.SetField(desktopupdaterelease.FieldArtifacts, field.TypeJSON, value)
		_node.Artifacts = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(desktopupdaterelease.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(desktopupdaterelease.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(desktopupdaterelease.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.PublishedBy(); ok {
		_spec.SetField(desktopupdaterelease.FieldPublishedBy, field.TypeInt64, value)
		_node.PublishedBy = &value
	}
	if value, ok := _c.mutation.WithdrawnBy(); ok {
		_spec.SetField(desktopupdaterelease.FieldWithdrawnBy, field.TypeInt64, value)
		_node.WithdrawnBy = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(desktopupdaterelease.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.WithdrawnAt(); ok {
		_spec.SetField(desktopupdaterelease.FieldWithdrawnAt, field.TypeTime, value)
		_node.WithdrawnAt = &value
	}
	if value, ok := _c.mutation.WithdrawalReason(); ok {
		_spec.SetField(desktopupdaterelease.FieldWithdrawalReason, field.TypeString, value)
		_node.WithdrawalReason = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopUpdateRelease.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopUpdateReleaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopUpdateReleaseCreate) OnConflict(opts ...sql.ConflictOption) *DesktopUpdateReleaseUpsertOne {
	_c.conflict = opts
	return &DesktopUpdateReleaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopUpdateRelease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopUpdateReleaseCreate) OnConflictColumns(columns ...string) *DesktopUpdateReleaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopUpdateReleaseUpsertOne{
		create: _c,
	}
}

type (
	// DesktopUpdateReleaseUpsertOne is the builder for "upsert"-ing
	//  one DesktopUpdateRelease node.
	DesktopUpdateReleaseUpsertOne struct {
		create *DesktopUpdateReleaseCreate
	}

	// DesktopUpdateReleaseUpsert is the "OnConflict" setter.
	DesktopUpdateReleaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopUpdateReleaseUpsert) SetUpdatedAt(v time.Time) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateUpdatedAt() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldUpdatedAt)
	return u
}

// SetVersion sets the "version" field.
func (u *DesktopUpdateReleaseUpsert) SetVersion(v string) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateVersion() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldVersion)
	return u
}

// SetNotes sets the "notes" field.
func (u *DesktopUpdateReleaseUpsert) SetNotes(v string) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateNotes() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldNotes)
	return u
}

// SetArtifacts sets the "artifacts" field.
func (u *DesktopUpdateReleaseUpsert) SetArtifacts(v jsontext.Value) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldArtifacts, v)
	return u
}

// UpdateArtifacts sets the "artifacts" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateArtifacts() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldArtifacts)
	return u
}

// SetStatus sets the "status" field.
func (u *DesktopUpdateReleaseUpsert) SetStatus(v string) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateStatus() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldStatus)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *DesktopUpdateReleaseUpsert) SetCreatedBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateCreatedBy() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DesktopUpdateReleaseUpsert) AddCreatedBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Add(desktopupdaterelease.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DesktopUpdateReleaseUpsert) ClearCreatedBy() *DesktopUpdateReleaseUpsert {
	u.SetNull(desktopupdaterelease.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *DesktopUpdateReleaseUpsert) SetUpdatedBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateUpdatedBy() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *DesktopUpdateReleaseUpsert) AddUpdatedBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Add(desktopupdaterelease.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *DesktopUpdateReleaseUpsert) ClearUpdatedBy() *DesktopUpdateReleaseUpsert {
	u.SetNull(desktopupdaterelease.FieldUpdatedBy)
	return u
}

// SetPublishedBy sets the "published_by" field.
func (u *DesktopUpdateReleaseUpsert) SetPublishedBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldPublishedBy, v)
	return u
}

// UpdatePublishedBy sets the "published_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdatePublishedBy() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldPublishedBy)
	return u
}

// AddPublishedBy adds v to the "published_by" field.
func (u *DesktopUpdateReleaseUpsert) AddPublishedBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Add(desktopupdaterelease.FieldPublishedBy, v)
	return u
}

// ClearPublishedBy clears the value of the "published_by" field.
func (u *DesktopUpdateReleaseUpsert) ClearPublishedBy() *DesktopUpdateReleaseUpsert {
	u.SetNull(desktopupdaterelease.FieldPublishedBy)
	return u
}

// SetWithdrawnBy sets the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsert) SetWithdrawnBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldWithdrawnBy, v)
	return u
}

// UpdateWithdrawnBy sets the "withdrawn_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateWithdrawnBy() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldWithdrawnBy)
	return u
}

// AddWithdrawnBy adds v to the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsert) AddWithdrawnBy(v int64) *DesktopUpdateReleaseUpsert {
	u.Add(desktopupdaterelease.FieldWithdrawnBy, v)
	return u
}

// ClearWithdrawnBy clears the value of the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsert) ClearWithdrawnBy() *DesktopUpdateReleaseUpsert {
	u.SetNull(desktopupdaterelease.FieldWithdrawnBy)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *DesktopUpdateReleaseUpsert) SetPublishedAt(v time.Time) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdatePublishedAt() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *DesktopUpdateReleaseUpsert) ClearPublishedAt() *DesktopUpdateReleaseUpsert {
	u.SetNull(desktopupdaterelease.FieldPublishedAt)
	return u
}

// SetWithdrawnAt sets the "withdrawn_at" field.
func (u *DesktopUpdateReleaseUpsert) SetWithdrawnAt(v time.Time) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldWithdrawnAt, v)
	return u
}

// UpdateWithdrawnAt sets the "withdrawn_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateWithdrawnAt() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldWithdrawnAt)
	return u
}

// ClearWithdrawnAt clears the value of the "withdrawn_at" field.
func (u *DesktopUpdateReleaseUpsert) ClearWithdrawnAt() *DesktopUpdateReleaseUpsert {
	u.SetNull(desktopupdaterelease.FieldWithdrawnAt)
	return u
}

// SetWithdrawalReason sets the "withdrawal_reason" field.
func (u *DesktopUpdateReleaseUpsert) SetWithdrawalReason(v string) *DesktopUpdateReleaseUpsert {
	u.Set(desktopupdaterelease.FieldWithdrawalReason, v)
	return u
}

// UpdateWithdrawalReason sets the "withdrawal_reason" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsert) UpdateWithdrawalReason() *DesktopUpdateReleaseUpsert {
	u.SetExcluded(desktopupdaterelease.FieldWithdrawalReason)
	return u
}

// ClearWithdrawalReason clears the value of the "withdrawal_reason" field.
func (u *DesktopUpdateReleaseUpsert) ClearWithdrawalReason() *DesktopUpdateReleaseUpsert {
	u.SetNull(desktopupdaterelease.FieldWithdrawalReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopUpdateRelease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopUpdateReleaseUpsertOne) UpdateNewValues() *DesktopUpdateReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(desktopupdaterelease.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.PublicID(); exists {
			s.SetIgnore(desktopupdaterelease.FieldPublicID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopUpdateRelease.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopUpdateReleaseUpsertOne) Ignore() *DesktopUpdateReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopUpdateReleaseUpsertOne) DoNothing() *DesktopUpdateReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopUpdateReleaseCreate.OnConflict
// documentation for more info.
func (u *DesktopUpdateReleaseUpsertOne) Update(set func(*DesktopUpdateReleaseUpsert)) *DesktopUpdateReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopUpdateReleaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopUpdateReleaseUpsertOne) SetUpdatedAt(v time.Time) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateUpdatedAt() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetVersion sets the "version" field.
func (u *DesktopUpdateReleaseUpsertOne) SetVersion(v string) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateVersion() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateVersion()
	})
}

// SetNotes sets the "notes" field.
func (u *DesktopUpdateReleaseUpsertOne) SetNotes(v string) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateNotes() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateNotes()
	})
}

// SetArtifacts sets the "artifacts" field.
func (u *DesktopUpdateReleaseUpsertOne) SetArtifacts(v jsontext.Value) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetArtifacts(v)
	})
}

// UpdateArtifacts sets the "artifacts" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateArtifacts() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateArtifacts()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopUpdateReleaseUpsertOne) SetStatus(v string) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateStatus() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DesktopUpdateReleaseUpsertOne) SetCreatedBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DesktopUpdateReleaseUpsertOne) AddCreatedBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateCreatedBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DesktopUpdateReleaseUpsertOne) ClearCreatedBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *DesktopUpdateReleaseUpsertOne) SetUpdatedBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *DesktopUpdateReleaseUpsertOne) AddUpdatedBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateUpdatedBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *DesktopUpdateReleaseUpsertOne) ClearUpdatedBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetPublishedBy sets the "published_by" field.
func (u *DesktopUpdateReleaseUpsertOne) SetPublishedBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetPublishedBy(v)
	})
}

// AddPublishedBy adds v to the "published_by" field.
func (u *DesktopUpdateReleaseUpsertOne) AddPublishedBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddPublishedBy(v)
	})
}

// UpdatePublishedBy sets the "published_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdatePublishedBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdatePublishedBy()
	})
}

// ClearPublishedBy clears the value of the "published_by" field.
func (u *DesktopUpdateReleaseUpsertOne) ClearPublishedBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearPublishedBy()
	})
}

// SetWithdrawnBy sets the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsertOne) SetWithdrawnBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetWithdrawnBy(v)
	})
}

// AddWithdrawnBy adds v to the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsertOne) AddWithdrawnBy(v int64) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddWithdrawnBy(v)
	})
}

// UpdateWithdrawnBy sets the "withdrawn_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateWithdrawnBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateWithdrawnBy()
	})
}

// ClearWithdrawnBy clears the value of the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsertOne) ClearWithdrawnBy() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearWithdrawnBy()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *DesktopUpdateReleaseUpsertOne) SetPublishedAt(v time.Time) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdatePublishedAt() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *DesktopUpdateReleaseUpsertOne) ClearPublishedAt() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearPublishedAt()
	})
}

// SetWithdrawnAt sets the "withdrawn_at" field.
func (u *DesktopUpdateReleaseUpsertOne) SetWithdrawnAt(v time.Time) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetWithdrawnAt(v)
	})
}

// UpdateWithdrawnAt sets the "withdrawn_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateWithdrawnAt() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateWithdrawnAt()
	})
}

// ClearWithdrawnAt clears the value of the "withdrawn_at" field.
func (u *DesktopUpdateReleaseUpsertOne) ClearWithdrawnAt() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearWithdrawnAt()
	})
}

// SetWithdrawalReason sets the "withdrawal_reason" field.
func (u *DesktopUpdateReleaseUpsertOne) SetWithdrawalReason(v string) *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetWithdrawalReason(v)
	})
}

// UpdateWithdrawalReason sets the "withdrawal_reason" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertOne) UpdateWithdrawalReason() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateWithdrawalReason()
	})
}

// ClearWithdrawalReason clears the value of the "withdrawal_reason" field.
func (u *DesktopUpdateReleaseUpsertOne) ClearWithdrawalReason() *DesktopUpdateReleaseUpsertOne {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearWithdrawalReason()
	})
}

// Exec executes the query.
func (u *DesktopUpdateReleaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopUpdateReleaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopUpdateReleaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopUpdateReleaseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopUpdateReleaseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopUpdateReleaseCreateBulk is the builder for creating many DesktopUpdateRelease entities in bulk.
type DesktopUpdateReleaseCreateBulk struct {
	config
	err      error
	builders []*DesktopUpdateReleaseCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopUpdateRelease entities in the database.
func (_c *DesktopUpdateReleaseCreateBulk) Save(ctx context.Context) ([]*DesktopUpdateRelease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopUpdateRelease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopUpdateReleaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopUpdateReleaseCreateBulk) SaveX(ctx context.Context) []*DesktopUpdateRelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopUpdateReleaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopUpdateReleaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopUpdateRelease.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopUpdateReleaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopUpdateReleaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopUpdateReleaseUpsertBulk {
	_c.conflict = opts
	return &DesktopUpdateReleaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopUpdateRelease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopUpdateReleaseCreateBulk) OnConflictColumns(columns ...string) *DesktopUpdateReleaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopUpdateReleaseUpsertBulk{
		create: _c,
	}
}

// DesktopUpdateReleaseUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopUpdateRelease nodes.
type DesktopUpdateReleaseUpsertBulk struct {
	create *DesktopUpdateReleaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopUpdateRelease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopUpdateReleaseUpsertBulk) UpdateNewValues() *DesktopUpdateReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(desktopupdaterelease.FieldCreatedAt)
			}
			if _, exists := b.mutation.PublicID(); exists {
				s.SetIgnore(desktopupdaterelease.FieldPublicID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopUpdateRelease.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopUpdateReleaseUpsertBulk) Ignore() *DesktopUpdateReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopUpdateReleaseUpsertBulk) DoNothing() *DesktopUpdateReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopUpdateReleaseCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopUpdateReleaseUpsertBulk) Update(set func(*DesktopUpdateReleaseUpsert)) *DesktopUpdateReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopUpdateReleaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetUpdatedAt(v time.Time) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateUpdatedAt() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetVersion sets the "version" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetVersion(v string) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateVersion() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateVersion()
	})
}

// SetNotes sets the "notes" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetNotes(v string) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateNotes() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateNotes()
	})
}

// SetArtifacts sets the "artifacts" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetArtifacts(v jsontext.Value) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetArtifacts(v)
	})
}

// UpdateArtifacts sets the "artifacts" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateArtifacts() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateArtifacts()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetStatus(v string) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateStatus() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetCreatedBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) AddCreatedBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateCreatedBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) ClearCreatedBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetUpdatedBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) AddUpdatedBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateUpdatedBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) ClearUpdatedBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetPublishedBy sets the "published_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetPublishedBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetPublishedBy(v)
	})
}

// AddPublishedBy adds v to the "published_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) AddPublishedBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddPublishedBy(v)
	})
}

// UpdatePublishedBy sets the "published_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdatePublishedBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdatePublishedBy()
	})
}

// ClearPublishedBy clears the value of the "published_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) ClearPublishedBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearPublishedBy()
	})
}

// SetWithdrawnBy sets the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetWithdrawnBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetWithdrawnBy(v)
	})
}

// AddWithdrawnBy adds v to the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) AddWithdrawnBy(v int64) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.AddWithdrawnBy(v)
	})
}

// UpdateWithdrawnBy sets the "withdrawn_by" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateWithdrawnBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateWithdrawnBy()
	})
}

// ClearWithdrawnBy clears the value of the "withdrawn_by" field.
func (u *DesktopUpdateReleaseUpsertBulk) ClearWithdrawnBy() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearWithdrawnBy()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetPublishedAt(v time.Time) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdatePublishedAt() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *DesktopUpdateReleaseUpsertBulk) ClearPublishedAt() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearPublishedAt()
	})
}

// SetWithdrawnAt sets the "withdrawn_at" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetWithdrawnAt(v time.Time) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetWithdrawnAt(v)
	})
}

// UpdateWithdrawnAt sets the "withdrawn_at" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateWithdrawnAt() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateWithdrawnAt()
	})
}

// ClearWithdrawnAt clears the value of the "withdrawn_at" field.
func (u *DesktopUpdateReleaseUpsertBulk) ClearWithdrawnAt() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearWithdrawnAt()
	})
}

// SetWithdrawalReason sets the "withdrawal_reason" field.
func (u *DesktopUpdateReleaseUpsertBulk) SetWithdrawalReason(v string) *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.SetWithdrawalReason(v)
	})
}

// UpdateWithdrawalReason sets the "withdrawal_reason" field to the value that was provided on create.
func (u *DesktopUpdateReleaseUpsertBulk) UpdateWithdrawalReason() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.UpdateWithdrawalReason()
	})
}

// ClearWithdrawalReason clears the value of the "withdrawal_reason" field.
func (u *DesktopUpdateReleaseUpsertBulk) ClearWithdrawalReason() *DesktopUpdateReleaseUpsertBulk {
	return u.Update(func(s *DesktopUpdateReleaseUpsert) {
		s.ClearWithdrawalReason()
	})
}

// Exec executes the query.
func (u *DesktopUpdateReleaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopUpdateReleaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopUpdateReleaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopUpdateReleaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
