// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktopmemberapikey"
)

// DesktopMemberAPIKeyCreate is the builder for creating a DesktopMemberAPIKey entity.
type DesktopMemberAPIKeyCreate struct {
	config
	mutation *DesktopMemberAPIKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMemberID sets the "member_id" field.
func (_c *DesktopMemberAPIKeyCreate) SetMemberID(v int64) *DesktopMemberAPIKeyCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *DesktopMemberAPIKeyCreate) SetAPIKeyID(v int64) *DesktopMemberAPIKeyCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *DesktopMemberAPIKeyCreate) SetAssignedAt(v time.Time) *DesktopMemberAPIKeyCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *DesktopMemberAPIKeyCreate) SetNillableAssignedAt(v *time.Time) *DesktopMemberAPIKeyCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetRetiredAt sets the "retired_at" field.
func (_c *DesktopMemberAPIKeyCreate) SetRetiredAt(v time.Time) *DesktopMemberAPIKeyCreate {
	_c.mutation.SetRetiredAt(v)
	return _c
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_c *DesktopMemberAPIKeyCreate) SetNillableRetiredAt(v *time.Time) *DesktopMemberAPIKeyCreate {
	if v != nil {
		_c.SetRetiredAt(*v)
	}
	return _c
}

// SetMember sets the "member" edge to the DesktopMember entity.
func (_c *DesktopMemberAPIKeyCreate) SetMember(v *DesktopMember) *DesktopMemberAPIKeyCreate {
	return _c.SetMemberID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *DesktopMemberAPIKeyCreate) SetAPIKey(v *APIKey) *DesktopMemberAPIKeyCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the DesktopMemberAPIKeyMutation object of the builder.
func (_c *DesktopMemberAPIKeyCreate) Mutation() *DesktopMemberAPIKeyMutation {
	return _c.mutation
}

// Save creates the DesktopMemberAPIKey in the database.
func (_c *DesktopMemberAPIKeyCreate) Save(ctx context.Context) (*DesktopMemberAPIKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopMemberAPIKeyCreate) SaveX(ctx context.Context) *DesktopMemberAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopMemberAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopMemberAPIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopMemberAPIKeyCreate) defaults() {
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := desktopmemberapikey.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopMemberAPIKeyCreate) check() error {
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "DesktopMemberAPIKey.member_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "DesktopMemberAPIKey.api_key_id"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "DesktopMemberAPIKey.assigned_at"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "DesktopMemberAPIKey.member"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "DesktopMemberAPIKey.api_key"`)}
	}
	return nil
}

func (_c *DesktopMemberAPIKeyCreate) sqlSave(ctx context.Context) (*DesktopMemberAPIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopMemberAPIKeyCreate) createSpec() (*DesktopMemberAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopMemberAPIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktopmemberapikey.Table, sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(desktopmemberapikey.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.RetiredAt(); ok {
		_spec.SetField(desktopmemberapikey.FieldRetiredAt, field.TypeTime, value)
		_node.RetiredAt = &value
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmemberapikey.MemberTable,
			Columns: []string{desktopmemberapikey.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   desktopmemberapikey.APIKeyTable,
			Columns: []string{desktopmemberapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopMemberAPIKey.Create().
//		SetMemberID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopMemberAPIKeyUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopMemberAPIKeyCreate) OnConflict(opts ...sql.ConflictOption) *DesktopMemberAPIKeyUpsertOne {
	_c.conflict = opts
	return &DesktopMemberAPIKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopMemberAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopMemberAPIKeyCreate) OnConflictColumns(columns ...string) *DesktopMemberAPIKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopMemberAPIKeyUpsertOne{
		create: _c,
	}
}

type (
	// DesktopMemberAPIKeyUpsertOne is the builder for "upsert"-ing
	//  one DesktopMemberAPIKey node.
	DesktopMemberAPIKeyUpsertOne struct {
		create *DesktopMemberAPIKeyCreate
	}

	// DesktopMemberAPIKeyUpsert is the "OnConflict" setter.
	DesktopMemberAPIKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetMemberID sets the "member_id" field.
func (u *DesktopMemberAPIKeyUpsert) SetMemberID(v int64) *DesktopMemberAPIKeyUpsert {
	u.Set(desktopmemberapikey.FieldMemberID, v)
	return u
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsert) UpdateMemberID() *DesktopMemberAPIKeyUpsert {
	u.SetExcluded(desktopmemberapikey.FieldMemberID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DesktopMemberAPIKeyUpsert) SetAPIKeyID(v int64) *DesktopMemberAPIKeyUpsert {
	u.Set(desktopmemberapikey.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsert) UpdateAPIKeyID() *DesktopMemberAPIKeyUpsert {
	u.SetExcluded(desktopmemberapikey.FieldAPIKeyID)
	return u
}

// SetRetiredAt sets the "retired_at" field.
func (u *DesktopMemberAPIKeyUpsert) SetRetiredAt(v time.Time) *DesktopMemberAPIKeyUpsert {
	u.Set(desktopmemberapikey.FieldRetiredAt, v)
	return u
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsert) UpdateRetiredAt() *DesktopMemberAPIKeyUpsert {
	u.SetExcluded(desktopmemberapikey.FieldRetiredAt)
	return u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *DesktopMemberAPIKeyUpsert) ClearRetiredAt() *DesktopMemberAPIKeyUpsert {
	u.SetNull(desktopmemberapikey.FieldRetiredAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopMemberAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopMemberAPIKeyUpsertOne) UpdateNewValues() *DesktopMemberAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.AssignedAt(); exists {
			s.SetIgnore(desktopmemberapikey.FieldAssignedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopMemberAPIKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopMemberAPIKeyUpsertOne) Ignore() *DesktopMemberAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopMemberAPIKeyUpsertOne) DoNothing() *DesktopMemberAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopMemberAPIKeyCreate.OnConflict
// documentation for more info.
func (u *DesktopMemberAPIKeyUpsertOne) Update(set func(*DesktopMemberAPIKeyUpsert)) *DesktopMemberAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopMemberAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *DesktopMemberAPIKeyUpsertOne) SetMemberID(v int64) *DesktopMemberAPIKeyUpsertOne {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsertOne) UpdateMemberID() *DesktopMemberAPIKeyUpsertOne {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.UpdateMemberID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DesktopMemberAPIKeyUpsertOne) SetAPIKeyID(v int64) *DesktopMemberAPIKeyUpsertOne {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsertOne) UpdateAPIKeyID() *DesktopMemberAPIKeyUpsertOne {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRetiredAt sets the "retired_at" field.
func (u *DesktopMemberAPIKeyUpsertOne) SetRetiredAt(v time.Time) *DesktopMemberAPIKeyUpsertOne {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.SetRetiredAt(v)
	})
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsertOne) UpdateRetiredAt() *DesktopMemberAPIKeyUpsertOne {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.UpdateRetiredAt()
	})
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *DesktopMemberAPIKeyUpsertOne) ClearRetiredAt() *DesktopMemberAPIKeyUpsertOne {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.ClearRetiredAt()
	})
}

// Exec executes the query.
func (u *DesktopMemberAPIKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopMemberAPIKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopMemberAPIKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopMemberAPIKeyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopMemberAPIKeyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopMemberAPIKeyCreateBulk is the builder for creating many DesktopMemberAPIKey entities in bulk.
type DesktopMemberAPIKeyCreateBulk struct {
	config
	err      error
	builders []*DesktopMemberAPIKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopMemberAPIKey entities in the database.
func (_c *DesktopMemberAPIKeyCreateBulk) Save(ctx context.Context) ([]*DesktopMemberAPIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopMemberAPIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopMemberAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopMemberAPIKeyCreateBulk) SaveX(ctx context.Context) []*DesktopMemberAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopMemberAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopMemberAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopMemberAPIKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopMemberAPIKeyUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopMemberAPIKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopMemberAPIKeyUpsertBulk {
	_c.conflict = opts
	return &DesktopMemberAPIKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopMemberAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopMemberAPIKeyCreateBulk) OnConflictColumns(columns ...string) *DesktopMemberAPIKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopMemberAPIKeyUpsertBulk{
		create: _c,
	}
}

// DesktopMemberAPIKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopMemberAPIKey nodes.
type DesktopMemberAPIKeyUpsertBulk struct {
	create *DesktopMemberAPIKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopMemberAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopMemberAPIKeyUpsertBulk) UpdateNewValues() *DesktopMemberAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.AssignedAt(); exists {
				s.SetIgnore(desktopmemberapikey.FieldAssignedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopMemberAPIKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopMemberAPIKeyUpsertBulk) Ignore() *DesktopMemberAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopMemberAPIKeyUpsertBulk) DoNothing() *DesktopMemberAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopMemberAPIKeyCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopMemberAPIKeyUpsertBulk) Update(set func(*DesktopMemberAPIKeyUpsert)) *DesktopMemberAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopMemberAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *DesktopMemberAPIKeyUpsertBulk) SetMemberID(v int64) *DesktopMemberAPIKeyUpsertBulk {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsertBulk) UpdateMemberID() *DesktopMemberAPIKeyUpsertBulk {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.UpdateMemberID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DesktopMemberAPIKeyUpsertBulk) SetAPIKeyID(v int64) *DesktopMemberAPIKeyUpsertBulk {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsertBulk) UpdateAPIKeyID() *DesktopMemberAPIKeyUpsertBulk {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRetiredAt sets the "retired_at" field.
func (u *DesktopMemberAPIKeyUpsertBulk) SetRetiredAt(v time.Time) *DesktopMemberAPIKeyUpsertBulk {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.SetRetiredAt(v)
	})
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *DesktopMemberAPIKeyUpsertBulk) UpdateRetiredAt() *DesktopMemberAPIKeyUpsertBulk {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.UpdateRetiredAt()
	})
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *DesktopMemberAPIKeyUpsertBulk) ClearRetiredAt() *DesktopMemberAPIKeyUpsertBulk {
	return u.Update(func(s *DesktopMemberAPIKeyUpsert) {
		s.ClearRetiredAt()
	})
}

// Exec executes the query.
func (u *DesktopMemberAPIKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopMemberAPIKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopMemberAPIKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopMemberAPIKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
