// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopOrganizationUpdate is the builder for updating DesktopOrganization entities.
type DesktopOrganizationUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopOrganizationMutation
}

// Where appends a list predicates to the DesktopOrganizationUpdate builder.
func (_u *DesktopOrganizationUpdate) Where(ps ...predicate.DesktopOrganization) *DesktopOrganizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopOrganizationUpdate) SetUpdatedAt(v time.Time) *DesktopOrganizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DesktopOrganizationUpdate) SetDeletedAt(v time.Time) *DesktopOrganizationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DesktopOrganizationUpdate) SetNillableDeletedAt(v *time.Time) *DesktopOrganizationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DesktopOrganizationUpdate) ClearDeletedAt() *DesktopOrganizationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *DesktopOrganizationUpdate) SetCode(v string) *DesktopOrganizationUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DesktopOrganizationUpdate) SetNillableCode(v *string) *DesktopOrganizationUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DesktopOrganizationUpdate) SetName(v string) *DesktopOrganizationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DesktopOrganizationUpdate) SetNillableName(v *string) *DesktopOrganizationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopOrganizationUpdate) SetStatus(v string) *DesktopOrganizationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopOrganizationUpdate) SetNillableStatus(v *string) *DesktopOrganizationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthVersion sets the "auth_version" field.
func (_u *DesktopOrganizationUpdate) SetAuthVersion(v int64) *DesktopOrganizationUpdate {
	_u.mutation.ResetAuthVersion()
	_u.mutation.SetAuthVersion(v)
	return _u
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_u *DesktopOrganizationUpdate) SetNillableAuthVersion(v *int64) *DesktopOrganizationUpdate {
	if v != nil {
		_u.SetAuthVersion(*v)
	}
	return _u
}

// AddAuthVersion adds value to the "auth_version" field.
func (_u *DesktopOrganizationUpdate) AddAuthVersion(v int64) *DesktopOrganizationUpdate {
	_u.mutation.AddAuthVersion(v)
	return _u
}

// SetGatewayUserID sets the "gateway_user_id" field.
func (_u *DesktopOrganizationUpdate) SetGatewayUserID(v int64) *DesktopOrganizationUpdate {
	_u.mutation.SetGatewayUserID(v)
	return _u
}

// SetNillableGatewayUserID sets the "gateway_user_id" field if the given value is not nil.
func (_u *DesktopOrganizationUpdate) SetNillableGatewayUserID(v *int64) *DesktopOrganizationUpdate {
	if v != nil {
		_u.SetGatewayUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DesktopOrganizationUpdate) SetGroupID(v int64) *DesktopOrganizationUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DesktopOrganizationUpdate) SetNillableGroupID(v *int64) *DesktopOrganizationUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetTargetConfig sets the "target_config" field.
func (_u *DesktopOrganizationUpdate) SetTargetConfig(v jsontext.Value) *DesktopOrganizationUpdate {
	_u.mutation.SetTargetConfig(v)
	return _u
}

// AppendTargetConfig appends value to the "target_config" field.
func (_u *DesktopOrganizationUpdate) AppendTargetConfig(v jsontext.Value) *DesktopOrganizationUpdate {
	_u.mutation.AppendTargetConfig(v)
	return _u
}

// ClearTargetConfig clears the value of the "target_config" field.
func (_u *DesktopOrganizationUpdate) ClearTargetConfig() *DesktopOrganizationUpdate {
	_u.mutation.ClearTargetConfig()
	return _u
}

// SetGatewayUser sets the "gateway_user" edge to the User entity.
func (_u *DesktopOrganizationUpdate) SetGatewayUser(v *User) *DesktopOrganizationUpdate {
	return _u.SetGatewayUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DesktopOrganizationUpdate) SetGroup(v *Group) *DesktopOrganizationUpdate {
	return _u.SetGroupID(v.ID)
}

// AddMemberIDs adds the "members" edge to the DesktopMember entity by IDs.
func (_u *DesktopOrganizationUpdate) AddMemberIDs(ids ...int64) *DesktopOrganizationUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the DesktopMember entity.
func (_u *DesktopOrganizationUpdate) AddMembers(v ...*DesktopMember) *DesktopOrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the DesktopOrganizationMutation object of the builder.
func (_u *DesktopOrganizationUpdate) Mutation() *DesktopOrganizationMutation {
	return _u.mutation
}

// ClearGatewayUser clears the "gateway_user" edge to the User entity.
func (_u *DesktopOrganizationUpdate) ClearGatewayUser() *DesktopOrganizationUpdate {
	_u.mutation.ClearGatewayUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DesktopOrganizationUpdate) ClearGroup() *DesktopOrganizationUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearMembers clears all "members" edges to the DesktopMember entity.
func (_u *DesktopOrganizationUpdate) ClearMembers() *DesktopOrganizationUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to DesktopMember entities by IDs.
func (_u *DesktopOrganizationUpdate) RemoveMemberIDs(ids ...int64) *DesktopOrganizationUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to DesktopMember entities.
func (_u *DesktopOrganizationUpdate) RemoveMembers(v ...*DesktopMember) *DesktopOrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopOrganizationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopOrganizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopOrganizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopOrganizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopOrganizationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if desktoporganization.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktoporganization.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := desktoporganization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopOrganizationUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := desktoporganization.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := desktoporganization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktoporganization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthVersion(); ok {
		if err := desktoporganization.AuthVersionValidator(v); err != nil {
			return &ValidationError{Name: "auth_version", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.auth_version": %w`, err)}
		}
	}
	if _u.mutation.GatewayUserCleared() && len(_u.mutation.GatewayUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopOrganization.gateway_user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopOrganization.group"`)
	}
	return nil
}

func (_u *DesktopOrganizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktoporganization.Table, desktoporganization.Columns, sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktoporganization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(desktoporganization.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(desktoporganization.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(desktoporganization.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(desktoporganization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktoporganization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthVersion(); ok {
		_spec.SetField(desktoporganization.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthVersion(); ok {
		_spec.AddField(desktoporganization.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetConfig(); ok {
		_spec.SetField(desktoporganization.FieldTargetConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTargetConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, desktoporganization.FieldTargetConfig, value)
		})
	}
	if _u.mutation.TargetConfigCleared() {
		_spec.ClearField(desktoporganization.FieldTargetConfig, field.TypeJSON)
	}
	if _u.mutation.GatewayUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GatewayUserTable,
			Columns: []string{desktoporganization.GatewayUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GatewayUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GatewayUserTable,
			Columns: []string{desktoporganization.GatewayUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GroupTable,
			Columns: []string{desktoporganization.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GroupTable,
			Columns: []string{desktoporganization.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktoporganization.MembersTable,
			Columns: []string{desktoporganization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktoporganization.MembersTable,
			Columns: []string{desktoporganization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktoporganization.MembersTable,
			Columns: []string{desktoporganization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktoporganization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopOrganizationUpdateOne is the builder for updating a single DesktopOrganization entity.
type DesktopOrganizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopOrganizationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopOrganizationUpdateOne) SetUpdatedAt(v time.Time) *DesktopOrganizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DesktopOrganizationUpdateOne) SetDeletedAt(v time.Time) *DesktopOrganizationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DesktopOrganizationUpdateOne) SetNillableDeletedAt(v *time.Time) *DesktopOrganizationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DesktopOrganizationUpdateOne) ClearDeletedAt() *DesktopOrganizationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *DesktopOrganizationUpdateOne) SetCode(v string) *DesktopOrganizationUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DesktopOrganizationUpdateOne) SetNillableCode(v *string) *DesktopOrganizationUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DesktopOrganizationUpdateOne) SetName(v string) *DesktopOrganizationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DesktopOrganizationUpdateOne) SetNillableName(v *string) *DesktopOrganizationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopOrganizationUpdateOne) SetStatus(v string) *DesktopOrganizationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopOrganizationUpdateOne) SetNillableStatus(v *string) *DesktopOrganizationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthVersion sets the "auth_version" field.
func (_u *DesktopOrganizationUpdateOne) SetAuthVersion(v int64) *DesktopOrganizationUpdateOne {
	_u.mutation.ResetAuthVersion()
	_u.mutation.SetAuthVersion(v)
	return _u
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_u *DesktopOrganizationUpdateOne) SetNillableAuthVersion(v *int64) *DesktopOrganizationUpdateOne {
	if v != nil {
		_u.SetAuthVersion(*v)
	}
	return _u
}

// AddAuthVersion adds value to the "auth_version" field.
func (_u *DesktopOrganizationUpdateOne) AddAuthVersion(v int64) *DesktopOrganizationUpdateOne {
	_u.mutation.AddAuthVersion(v)
	return _u
}

// SetGatewayUserID sets the "gateway_user_id" field.
func (_u *DesktopOrganizationUpdateOne) SetGatewayUserID(v int64) *DesktopOrganizationUpdateOne {
	_u.mutation.SetGatewayUserID(v)
	return _u
}

// SetNillableGatewayUserID sets the "gateway_user_id" field if the given value is not nil.
func (_u *DesktopOrganizationUpdateOne) SetNillableGatewayUserID(v *int64) *DesktopOrganizationUpdateOne {
	if v != nil {
		_u.SetGatewayUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DesktopOrganizationUpdateOne) SetGroupID(v int64) *DesktopOrganizationUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DesktopOrganizationUpdateOne) SetNillableGroupID(v *int64) *DesktopOrganizationUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetTargetConfig sets the "target_config" field.
func (_u *DesktopOrganizationUpdateOne) SetTargetConfig(v jsontext.Value) *DesktopOrganizationUpdateOne {
	_u.mutation.SetTargetConfig(v)
	return _u
}

// AppendTargetConfig appends value to the "target_config" field.
func (_u *DesktopOrganizationUpdateOne) AppendTargetConfig(v jsontext.Value) *DesktopOrganizationUpdateOne {
	_u.mutation.AppendTargetConfig(v)
	return _u
}

// ClearTargetConfig clears the value of the "target_config" field.
func (_u *DesktopOrganizationUpdateOne) ClearTargetConfig() *DesktopOrganizationUpdateOne {
	_u.mutation.ClearTargetConfig()
	return _u
}

// SetGatewayUser sets the "gateway_user" edge to the User entity.
func (_u *DesktopOrganizationUpdateOne) SetGatewayUser(v *User) *DesktopOrganizationUpdateOne {
	return _u.SetGatewayUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DesktopOrganizationUpdateOne) SetGroup(v *Group) *DesktopOrganizationUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddMemberIDs adds the "members" edge to the DesktopMember entity by IDs.
func (_u *DesktopOrganizationUpdateOne) AddMemberIDs(ids ...int64) *DesktopOrganizationUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the DesktopMember entity.
func (_u *DesktopOrganizationUpdateOne) AddMembers(v ...*DesktopMember) *DesktopOrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the DesktopOrganizationMutation object of the builder.
func (_u *DesktopOrganizationUpdateOne) Mutation() *DesktopOrganizationMutation {
	return _u.mutation
}

// ClearGatewayUser clears the "gateway_user" edge to the User entity.
func (_u *DesktopOrganizationUpdateOne) ClearGatewayUser() *DesktopOrganizationUpdateOne {
	_u.mutation.ClearGatewayUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DesktopOrganizationUpdateOne) ClearGroup() *DesktopOrganizationUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearMembers clears all "members" edges to the DesktopMember entity.
func (_u *DesktopOrganizationUpdateOne) ClearMembers() *DesktopOrganizationUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to DesktopMember entities by IDs.
func (_u *DesktopOrganizationUpdateOne) RemoveMemberIDs(ids ...int64) *DesktopOrganizationUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to DesktopMember entities.
func (_u *DesktopOrganizationUpdateOne) RemoveMembers(v ...*DesktopMember) *DesktopOrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the DesktopOrganizationUpdate builder.
func (_u *DesktopOrganizationUpdateOne) Where(ps ...predicate.DesktopOrganization) *DesktopOrganizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopOrganizationUpdateOne) Select(field string, fields ...string) *DesktopOrganizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopOrganization entity.
func (_u *DesktopOrganizationUpdateOne) Save(ctx context.Context) (*DesktopOrganization, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopOrganizationUpdateOne) SaveX(ctx context.Context) *DesktopOrganization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopOrganizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopOrganizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopOrganizationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if desktoporganization.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktoporganization.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := desktoporganization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopOrganizationUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := desktoporganization.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := desktoporganization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktoporganization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthVersion(); ok {
		if err := desktoporganization.AuthVersionValidator(v); err != nil {
			return &ValidationError{Name: "auth_version", err: fmt.Errorf(`ent: validator failed for field "DesktopOrganization.auth_version": %w`, err)}
		}
	}
	if _u.mutation.GatewayUserCleared() && len(_u.mutation.GatewayUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopOrganization.gateway_user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopOrganization.group"`)
	}
	return nil
}

func (_u *DesktopOrganizationUpdateOne) sqlSave(ctx context.Context) (_node *DesktopOrganization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktoporganization.Table, desktoporganization.Columns, sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopOrganization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktoporganization.FieldID)
		for _, f := range fields {
			if !desktoporganization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktoporganization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktoporganization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(desktoporganization.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(desktoporganization.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(desktoporganization.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(desktoporganization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktoporganization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthVersion(); ok {
		_spec.SetField(desktoporganization.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthVersion(); ok {
		_spec.AddField(desktoporganization.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetConfig(); ok {
		_spec.SetField(desktoporganization.FieldTargetConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTargetConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, desktoporganization.FieldTargetConfig, value)
		})
	}
	if _u.mutation.TargetConfigCleared() {
		_spec.ClearField(desktoporganization.FieldTargetConfig, field.TypeJSON)
	}
	if _u.mutation.GatewayUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GatewayUserTable,
			Columns: []string{desktoporganization.GatewayUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GatewayUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GatewayUserTable,
			Columns: []string{desktoporganization.GatewayUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GroupTable,
			Columns: []string{desktoporganization.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktoporganization.GroupTable,
			Columns: []string{desktoporganization.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktoporganization.MembersTable,
			Columns: []string{desktoporganization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktoporganization.MembersTable,
			Columns: []string{desktoporganization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktoporganization.MembersTable,
			Columns: []string{desktoporganization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DesktopOrganization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktoporganization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
