// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
)

// DesktopMember is the model entity for the DesktopMember schema.
type DesktopMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int64 `json:"organization_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// NameNormalized holds the value of the "name_normalized" field.
	NameNormalized string `json:"name_normalized,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AuthVersion holds the value of the "auth_version" field.
	AuthVersion int64 `json:"auth_version,omitempty"`
	// APIKeySuspendedByOrganization holds the value of the "api_key_suspended_by_organization" field.
	APIKeySuspendedByOrganization bool `json:"api_key_suspended_by_organization,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DesktopMemberQuery when eager-loading is set.
	Edges        DesktopMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DesktopMemberEdges holds the relations/edges for other nodes in the graph.
type DesktopMemberEdges struct {
	// Organization holds the value of the organization edge.
	Organization *DesktopOrganization `json:"organization,omitempty"`
	// APIKeyAssignments holds the value of the api_key_assignments edge.
	APIKeyAssignments []*DesktopMemberAPIKey `json:"api_key_assignments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopMemberEdges) OrganizationOrErr() (*DesktopOrganization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: desktoporganization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// APIKeyAssignmentsOrErr returns the APIKeyAssignments value or an error if the edge
// was not loaded in eager-loading.
func (e DesktopMemberEdges) APIKeyAssignmentsOrErr() ([]*DesktopMemberAPIKey, error) {
	if e.loadedTypes[1] {
		return e.APIKeyAssignments, nil
	}
	return nil, &NotLoadedError{edge: "api_key_assignments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DesktopMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case desktopmember.FieldAPIKeySuspendedByOrganization:
			values[i] = new(sql.NullBool)
		case desktopmember.FieldID, desktopmember.FieldOrganizationID, desktopmember.FieldAuthVersion:
			values[i] = new(sql.NullInt64)
		case desktopmember.FieldPublicID, desktopmember.FieldName, desktopmember.FieldNameNormalized, desktopmember.FieldPhone, desktopmember.FieldStatus:
			values[i] = new(sql.NullString)
		case desktopmember.FieldCreatedAt, desktopmember.FieldUpdatedAt, desktopmember.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DesktopMember fields.
func (_m *DesktopMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case desktopmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case desktopmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case desktopmember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case desktopmember.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case desktopmember.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case desktopmember.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.Int64
			}
		case desktopmember.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case desktopmember.FieldNameNormalized:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_normalized", values[i])
			} else if value.Valid {
				_m.NameNormalized = value.String
			}
		case desktopmember.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case desktopmember.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case desktopmember.FieldAuthVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auth_version", values[i])
			} else if value.Valid {
				_m.AuthVersion = value.Int64
			}
		case desktopmember.FieldAPIKeySuspendedByOrganization:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_suspended_by_organization", values[i])
			} else if value.Valid {
				_m.APIKeySuspendedByOrganization = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DesktopMember.
// This includes values selected through modifiers, order, etc.
func (_m *DesktopMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the DesktopMember entity.
func (_m *DesktopMember) QueryOrganization() *DesktopOrganizationQuery {
	return NewDesktopMemberClient(_m.config).QueryOrganization(_m)
}

// QueryAPIKeyAssignments queries the "api_key_assignments" edge of the DesktopMember entity.
func (_m *DesktopMember) QueryAPIKeyAssignments() *DesktopMemberAPIKeyQuery {
	return NewDesktopMemberClient(_m.config).QueryAPIKeyAssignments(_m)
}

// Update returns a builder for updating this DesktopMember.
// Note that you need to call DesktopMember.Unwrap() before calling this method if this DesktopMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DesktopMember) Update() *DesktopMemberUpdateOne {
	return NewDesktopMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DesktopMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DesktopMember) Unwrap() *DesktopMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DesktopMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DesktopMember) String() string {
	var builder strings.Builder
	builder.WriteString("DesktopMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("name_normalized=")
	builder.WriteString(_m.NameNormalized)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("auth_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthVersion))
	builder.WriteString(", ")
	builder.WriteString("api_key_suspended_by_organization=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeySuspendedByOrganization))
	builder.WriteByte(')')
	return builder.String()
}

// DesktopMembers is a parsable slice of DesktopMember.
type DesktopMembers []*DesktopMember
