// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktopmemberapikey"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
)

// DesktopMemberCreate is the builder for creating a DesktopMember entity.
type DesktopMemberCreate struct {
	config
	mutation *DesktopMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesktopMemberCreate) SetCreatedAt(v time.Time) *DesktopMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesktopMemberCreate) SetNillableCreatedAt(v *time.Time) *DesktopMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesktopMemberCreate) SetUpdatedAt(v time.Time) *DesktopMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesktopMemberCreate) SetNillableUpdatedAt(v *time.Time) *DesktopMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DesktopMemberCreate) SetDeletedAt(v time.Time) *DesktopMemberCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DesktopMemberCreate) SetNillableDeletedAt(v *time.Time) *DesktopMemberCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *DesktopMemberCreate) SetPublicID(v string) *DesktopMemberCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *DesktopMemberCreate) SetOrganizationID(v int64) *DesktopMemberCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DesktopMemberCreate) SetName(v string) *DesktopMemberCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNameNormalized sets the "name_normalized" field.
func (_c *DesktopMemberCreate) SetNameNormalized(v string) *DesktopMemberCreate {
	_c.mutation.SetNameNormalized(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *DesktopMemberCreate) SetPhone(v string) *DesktopMemberCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DesktopMemberCreate) SetStatus(v string) *DesktopMemberCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DesktopMemberCreate) SetNillableStatus(v *string) *DesktopMemberCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAuthVersion sets the "auth_version" field.
func (_c *DesktopMemberCreate) SetAuthVersion(v int64) *DesktopMemberCreate {
	_c.mutation.SetAuthVersion(v)
	return _c
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_c *DesktopMemberCreate) SetNillableAuthVersion(v *int64) *DesktopMemberCreate {
	if v != nil {
		_c.SetAuthVersion(*v)
	}
	return _c
}

// SetAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field.
func (_c *DesktopMemberCreate) SetAPIKeySuspendedByOrganization(v bool) *DesktopMemberCreate {
	_c.mutation.SetAPIKeySuspendedByOrganization(v)
	return _c
}

// SetNillableAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field if the given value is not nil.
func (_c *DesktopMemberCreate) SetNillableAPIKeySuspendedByOrganization(v *bool) *DesktopMemberCreate {
	if v != nil {
		_c.SetAPIKeySuspendedByOrganization(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the DesktopOrganization entity.
func (_c *DesktopMemberCreate) SetOrganization(v *DesktopOrganization) *DesktopMemberCreate {
	return _c.SetOrganizationID(v.ID)
}

// AddAPIKeyAssignmentIDs adds the "api_key_assignments" edge to the DesktopMemberAPIKey entity by IDs.
func (_c *DesktopMemberCreate) AddAPIKeyAssignmentIDs(ids ...int64) *DesktopMemberCreate {
	_c.mutation.AddAPIKeyAssignmentIDs(ids...)
	return _c
}

// AddAPIKeyAssignments adds the "api_key_assignments" edges to the DesktopMemberAPIKey entity.
func (_c *DesktopMemberCreate) AddAPIKeyAssignments(v ...*DesktopMemberAPIKey) *DesktopMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyAssignmentIDs(ids...)
}

// Mutation returns the DesktopMemberMutation object of the builder.
func (_c *DesktopMemberCreate) Mutation() *DesktopMemberMutation {
	return _c.mutation
}

// Save creates the DesktopMember in the database.
func (_c *DesktopMemberCreate) Save(ctx context.Context) (*DesktopMember, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopMemberCreate) SaveX(ctx context.Context) *DesktopMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopMemberCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if desktopmember.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktopmember.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := desktopmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if desktopmember.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized desktopmember.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := desktopmember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := desktopmember.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AuthVersion(); !ok {
		v := desktopmember.DefaultAuthVersion
		_c.mutation.SetAuthVersion(v)
	}
	if _, ok := _c.mutation.APIKeySuspendedByOrganization(); !ok {
		v := desktopmember.DefaultAPIKeySuspendedByOrganization
		_c.mutation.SetAPIKeySuspendedByOrganization(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DesktopMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DesktopMember.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "DesktopMember.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := desktopmember.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "DesktopMember.organization_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DesktopMember.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := desktopmember.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameNormalized(); !ok {
		return &ValidationError{Name: "name_normalized", err: errors.New(`ent: missing required field "DesktopMember.name_normalized"`)}
	}
	if v, ok := _c.mutation.NameNormalized(); ok {
		if err := desktopmember.NameNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "name_normalized", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.name_normalized": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "DesktopMember.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := desktopmember.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DesktopMember.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := desktopmember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthVersion(); !ok {
		return &ValidationError{Name: "auth_version", err: errors.New(`ent: missing required field "DesktopMember.auth_version"`)}
	}
	if v, ok := _c.mutation.AuthVersion(); ok {
		if err := desktopmember.AuthVersionValidator(v); err != nil {
			return &ValidationError{Name: "auth_version", err: fmt.Errorf(`ent: validator failed for field "DesktopMember.auth_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeySuspendedByOrganization(); !ok {
		return &ValidationError{Name: "api_key_suspended_by_organization", err: errors.New(`ent: missing required field "DesktopMember.api_key_suspended_by_organization"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "DesktopMember.organization"`)}
	}
	return nil
}

func (_c *DesktopMemberCreate) sqlSave(ctx context.Context) (*DesktopMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopMemberCreate) createSpec() (*DesktopMember, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktopmember.Table, sqlgraph.NewFieldSpec(desktopmember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(desktopmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(desktopmember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(desktopmember.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(desktopmember.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NameNormalized(); ok {
		_spec.SetField(desktopmember.FieldNameNormalized, field.TypeString, value)
		_node.NameNormalized = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(desktopmember.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(desktopmember.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AuthVersion(); ok {
		_spec.SetField(desktopmember.FieldAuthVersion, field.TypeInt64, value)
		_node.AuthVersion = value
	}
	if value, ok := _c.mutation.APIKeySuspendedByOrganization(); ok {
		_spec.SetField(desktopmember.FieldAPIKeySuspendedByOrganization, field.TypeBool, value)
		_node.APIKeySuspendedByOrganization = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmember.OrganizationTable,
			Columns: []string{desktopmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktoporganization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopmember.APIKeyAssignmentsTable,
			Columns: []string{desktopmember.APIKeyAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopmemberapikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopMemberCreate) OnConflict(opts ...sql.ConflictOption) *DesktopMemberUpsertOne {
	_c.conflict = opts
	return &DesktopMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopMemberCreate) OnConflictColumns(columns ...string) *DesktopMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopMemberUpsertOne{
		create: _c,
	}
}

type (
	// DesktopMemberUpsertOne is the builder for "upsert"-ing
	//  one DesktopMember node.
	DesktopMemberUpsertOne struct {
		create *DesktopMemberCreate
	}

	// DesktopMemberUpsert is the "OnConflict" setter.
	DesktopMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopMemberUpsert) SetUpdatedAt(v time.Time) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateUpdatedAt() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DesktopMemberUpsert) SetDeletedAt(v time.Time) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateDeletedAt() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DesktopMemberUpsert) ClearDeletedAt() *DesktopMemberUpsert {
	u.SetNull(desktopmember.FieldDeletedAt)
	return u
}

// SetOrganizationID sets the "organization_id" field.
func (u *DesktopMemberUpsert) SetOrganizationID(v int64) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldOrganizationID, v)
	return u
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateOrganizationID() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldOrganizationID)
	return u
}

// SetName sets the "name" field.
func (u *DesktopMemberUpsert) SetName(v string) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateName() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldName)
	return u
}

// SetNameNormalized sets the "name_normalized" field.
func (u *DesktopMemberUpsert) SetNameNormalized(v string) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldNameNormalized, v)
	return u
}

// UpdateNameNormalized sets the "name_normalized" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateNameNormalized() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldNameNormalized)
	return u
}

// SetPhone sets the "phone" field.
func (u *DesktopMemberUpsert) SetPhone(v string) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdatePhone() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldPhone)
	return u
}

// SetStatus sets the "status" field.
func (u *DesktopMemberUpsert) SetStatus(v string) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateStatus() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldStatus)
	return u
}

// SetAuthVersion sets the "auth_version" field.
func (u *DesktopMemberUpsert) SetAuthVersion(v int64) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldAuthVersion, v)
	return u
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateAuthVersion() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldAuthVersion)
	return u
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *DesktopMemberUpsert) AddAuthVersion(v int64) *DesktopMemberUpsert {
	u.Add(desktopmember.FieldAuthVersion, v)
	return u
}

// SetAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field.
func (u *DesktopMemberUpsert) SetAPIKeySuspendedByOrganization(v bool) *DesktopMemberUpsert {
	u.Set(desktopmember.FieldAPIKeySuspendedByOrganization, v)
	return u
}

// UpdateAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field to the value that was provided on create.
func (u *DesktopMemberUpsert) UpdateAPIKeySuspendedByOrganization() *DesktopMemberUpsert {
	u.SetExcluded(desktopmember.FieldAPIKeySuspendedByOrganization)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopMemberUpsertOne) UpdateNewValues() *DesktopMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(desktopmember.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.PublicID(); exists {
			s.SetIgnore(desktopmember.FieldPublicID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopMemberUpsertOne) Ignore() *DesktopMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopMemberUpsertOne) DoNothing() *DesktopMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopMemberCreate.OnConflict
// documentation for more info.
func (u *DesktopMemberUpsertOne) Update(set func(*DesktopMemberUpsert)) *DesktopMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopMemberUpsertOne) SetUpdatedAt(v time.Time) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateUpdatedAt() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DesktopMemberUpsertOne) SetDeletedAt(v time.Time) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateDeletedAt() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DesktopMemberUpsertOne) ClearDeletedAt() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *DesktopMemberUpsertOne) SetOrganizationID(v int64) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateOrganizationID() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetName sets the "name" field.
func (u *DesktopMemberUpsertOne) SetName(v string) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateName() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateName()
	})
}

// SetNameNormalized sets the "name_normalized" field.
func (u *DesktopMemberUpsertOne) SetNameNormalized(v string) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetNameNormalized(v)
	})
}

// UpdateNameNormalized sets the "name_normalized" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateNameNormalized() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateNameNormalized()
	})
}

// SetPhone sets the "phone" field.
func (u *DesktopMemberUpsertOne) SetPhone(v string) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdatePhone() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdatePhone()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopMemberUpsertOne) SetStatus(v string) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateStatus() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *DesktopMemberUpsertOne) SetAuthVersion(v int64) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *DesktopMemberUpsertOne) AddAuthVersion(v int64) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateAuthVersion() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateAuthVersion()
	})
}

// SetAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field.
func (u *DesktopMemberUpsertOne) SetAPIKeySuspendedByOrganization(v bool) *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetAPIKeySuspendedByOrganization(v)
	})
}

// UpdateAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field to the value that was provided on create.
func (u *DesktopMemberUpsertOne) UpdateAPIKeySuspendedByOrganization() *DesktopMemberUpsertOne {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateAPIKeySuspendedByOrganization()
	})
}

// Exec executes the query.
func (u *DesktopMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopMemberCreateBulk is the builder for creating many DesktopMember entities in bulk.
type DesktopMemberCreateBulk struct {
	config
	err      error
	builders []*DesktopMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopMember entities in the database.
func (_c *DesktopMemberCreateBulk) Save(ctx context.Context) ([]*DesktopMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopMemberCreateBulk) SaveX(ctx context.Context) []*DesktopMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopMemberUpsertBulk {
	_c.conflict = opts
	return &DesktopMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopMemberCreateBulk) OnConflictColumns(columns ...string) *DesktopMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopMemberUpsertBulk{
		create: _c,
	}
}

// DesktopMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopMember nodes.
type DesktopMemberUpsertBulk struct {
	create *DesktopMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopMemberUpsertBulk) UpdateNewValues() *DesktopMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(desktopmember.FieldCreatedAt)
			}
			if _, exists := b.mutation.PublicID(); exists {
				s.SetIgnore(desktopmember.FieldPublicID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopMemberUpsertBulk) Ignore() *DesktopMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopMemberUpsertBulk) DoNothing() *DesktopMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopMemberCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopMemberUpsertBulk) Update(set func(*DesktopMemberUpsert)) *DesktopMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopMemberUpsertBulk) SetUpdatedAt(v time.Time) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateUpdatedAt() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DesktopMemberUpsertBulk) SetDeletedAt(v time.Time) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateDeletedAt() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DesktopMemberUpsertBulk) ClearDeletedAt() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *DesktopMemberUpsertBulk) SetOrganizationID(v int64) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateOrganizationID() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetName sets the "name" field.
func (u *DesktopMemberUpsertBulk) SetName(v string) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateName() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateName()
	})
}

// SetNameNormalized sets the "name_normalized" field.
func (u *DesktopMemberUpsertBulk) SetNameNormalized(v string) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetNameNormalized(v)
	})
}

// UpdateNameNormalized sets the "name_normalized" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateNameNormalized() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateNameNormalized()
	})
}

// SetPhone sets the "phone" field.
func (u *DesktopMemberUpsertBulk) SetPhone(v string) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdatePhone() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdatePhone()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopMemberUpsertBulk) SetStatus(v string) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateStatus() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *DesktopMemberUpsertBulk) SetAuthVersion(v int64) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *DesktopMemberUpsertBulk) AddAuthVersion(v int64) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateAuthVersion() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateAuthVersion()
	})
}

// SetAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field.
func (u *DesktopMemberUpsertBulk) SetAPIKeySuspendedByOrganization(v bool) *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.SetAPIKeySuspendedByOrganization(v)
	})
}

// UpdateAPIKeySuspendedByOrganization sets the "api_key_suspended_by_organization" field to the value that was provided on create.
func (u *DesktopMemberUpsertBulk) UpdateAPIKeySuspendedByOrganization() *DesktopMemberUpsertBulk {
	return u.Update(func(s *DesktopMemberUpsert) {
		s.UpdateAPIKeySuspendedByOrganization()
	})
}

// Exec executes the query.
func (u *DesktopMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
