// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/desktopupdaterelease"
)

// DesktopUpdateRelease is the model entity for the DesktopUpdateRelease schema.
type DesktopUpdateRelease struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Artifacts holds the value of the "artifacts" field.
	Artifacts jsontext.Value `json:"artifacts,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// PublishedBy holds the value of the "published_by" field.
	PublishedBy *int64 `json:"published_by,omitempty"`
	// WithdrawnBy holds the value of the "withdrawn_by" field.
	WithdrawnBy *int64 `json:"withdrawn_by,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// WithdrawnAt holds the value of the "withdrawn_at" field.
	WithdrawnAt *time.Time `json:"withdrawn_at,omitempty"`
	// WithdrawalReason holds the value of the "withdrawal_reason" field.
	WithdrawalReason *string `json:"withdrawal_reason,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DesktopUpdateRelease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case desktopupdaterelease.FieldArtifacts:
			values[i] = new([]byte)
		case desktopupdaterelease.FieldID, desktopupdaterelease.FieldCreatedBy, desktopupdaterelease.FieldUpdatedBy, desktopupdaterelease.FieldPublishedBy, desktopupdaterelease.FieldWithdrawnBy:
			values[i] = new(sql.NullInt64)
		case desktopupdaterelease.FieldPublicID, desktopupdaterelease.FieldVersion, desktopupdaterelease.FieldNotes, desktopupdaterelease.FieldStatus, desktopupdaterelease.FieldWithdrawalReason:
			values[i] = new(sql.NullString)
		case desktopupdaterelease.FieldCreatedAt, desktopupdaterelease.FieldUpdatedAt, desktopupdaterelease.FieldPublishedAt, desktopupdaterelease.FieldWithdrawnAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DesktopUpdateRelease fields.
func (_m *DesktopUpdateRelease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case desktopupdaterelease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case desktopupdaterelease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case desktopupdaterelease.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case desktopupdaterelease.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case desktopupdaterelease.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case desktopupdaterelease.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case desktopupdaterelease.FieldArtifacts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field artifacts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Artifacts); err != nil {
					return fmt.Errorf("unmarshal field artifacts: %w", err)
				}
			}
		case desktopupdaterelease.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case desktopupdaterelease.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case desktopupdaterelease.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		case desktopupdaterelease.FieldPublishedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field published_by", values[i])
			} else if value.Valid {
				_m.PublishedBy = new(int64)
				*_m.PublishedBy = value.Int64
			}
		case desktopupdaterelease.FieldWithdrawnBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field withdrawn_by", values[i])
			} else if value.Valid {
				_m.WithdrawnBy = new(int64)
				*_m.WithdrawnBy = value.Int64
			}
		case desktopupdaterelease.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case desktopupdaterelease.FieldWithdrawnAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field withdrawn_at", values[i])
			} else if value.Valid {
				_m.WithdrawnAt = new(time.Time)
				*_m.WithdrawnAt = value.Time
			}
		case desktopupdaterelease.FieldWithdrawalReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field withdrawal_reason", values[i])
			} else if value.Valid {
				_m.WithdrawalReason = new(string)
				*_m.WithdrawalReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DesktopUpdateRelease.
// This includes values selected through modifiers, order, etc.
func (_m *DesktopUpdateRelease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DesktopUpdateRelease.
// Note that you need to call DesktopUpdateRelease.Unwrap() before calling this method if this DesktopUpdateRelease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DesktopUpdateRelease) Update() *DesktopUpdateReleaseUpdateOne {
	return NewDesktopUpdateReleaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DesktopUpdateRelease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DesktopUpdateRelease) Unwrap() *DesktopUpdateRelease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DesktopUpdateRelease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DesktopUpdateRelease) String() string {
	var builder strings.Builder
	builder.WriteString("DesktopUpdateRelease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("artifacts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Artifacts))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PublishedBy; v != nil {
		builder.WriteString("published_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WithdrawnBy; v != nil {
		builder.WriteString("withdrawn_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WithdrawnAt; v != nil {
		builder.WriteString("withdrawn_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WithdrawalReason; v != nil {
		builder.WriteString("withdrawal_reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// DesktopUpdateReleases is a parsable slice of DesktopUpdateRelease.
type DesktopUpdateReleases []*DesktopUpdateRelease
