// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopconversationrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopConversationRecordUpdate is the builder for updating DesktopConversationRecord entities.
type DesktopConversationRecordUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopConversationRecordMutation
}

// Where appends a list predicates to the DesktopConversationRecordUpdate builder.
func (_u *DesktopConversationRecordUpdate) Where(ps ...predicate.DesktopConversationRecord) *DesktopConversationRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the DesktopConversationRecordMutation object of the builder.
func (_u *DesktopConversationRecordUpdate) Mutation() *DesktopConversationRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopConversationRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopConversationRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopConversationRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopConversationRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopConversationRecordUpdate) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopConversationRecord.organization"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopConversationRecord.member"`)
	}
	return nil
}

func (_u *DesktopConversationRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopconversationrecord.Table, desktopconversationrecord.Columns, sqlgraph.NewFieldSpec(desktopconversationrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SourceTurnIDCleared() {
		_spec.ClearField(desktopconversationrecord.FieldSourceTurnID, field.TypeString)
	}
	if _u.mutation.CwdCleared() {
		_spec.ClearField(desktopconversationrecord.FieldCwd, field.TypeString)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(desktopconversationrecord.FieldResponse, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopconversationrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopConversationRecordUpdateOne is the builder for updating a single DesktopConversationRecord entity.
type DesktopConversationRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopConversationRecordMutation
}

// Mutation returns the DesktopConversationRecordMutation object of the builder.
func (_u *DesktopConversationRecordUpdateOne) Mutation() *DesktopConversationRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the DesktopConversationRecordUpdate builder.
func (_u *DesktopConversationRecordUpdateOne) Where(ps ...predicate.DesktopConversationRecord) *DesktopConversationRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopConversationRecordUpdateOne) Select(field string, fields ...string) *DesktopConversationRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopConversationRecord entity.
func (_u *DesktopConversationRecordUpdateOne) Save(ctx context.Context) (*DesktopConversationRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopConversationRecordUpdateOne) SaveX(ctx context.Context) *DesktopConversationRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopConversationRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopConversationRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopConversationRecordUpdateOne) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopConversationRecord.organization"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopConversationRecord.member"`)
	}
	return nil
}

func (_u *DesktopConversationRecordUpdateOne) sqlSave(ctx context.Context) (_node *DesktopConversationRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopconversationrecord.Table, desktopconversationrecord.Columns, sqlgraph.NewFieldSpec(desktopconversationrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopConversationRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopconversationrecord.FieldID)
		for _, f := range fields {
			if !desktopconversationrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopconversationrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SourceTurnIDCleared() {
		_spec.ClearField(desktopconversationrecord.FieldSourceTurnID, field.TypeString)
	}
	if _u.mutation.CwdCleared() {
		_spec.ClearField(desktopconversationrecord.FieldCwd, field.TypeString)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(desktopconversationrecord.FieldResponse, field.TypeJSON)
	}
	_node = &DesktopConversationRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopconversationrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
