// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/desktopconversationrecord"
	"github.com/Wei-Shaw/sub2api/ent/desktopmember"
	"github.com/Wei-Shaw/sub2api/ent/desktoporganization"
	"github.com/google/uuid"
)

// DesktopConversationRecord is the model entity for the DesktopConversationRecord schema.
type DesktopConversationRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RecordID holds the value of the "record_id" field.
	RecordID uuid.UUID `json:"record_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int64 `json:"organization_id,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID int64 `json:"member_id,omitempty"`
	// InstallationID holds the value of the "installation_id" field.
	InstallationID uuid.UUID `json:"installation_id,omitempty"`
	// Client holds the value of the "client" field.
	Client string `json:"client,omitempty"`
	// SourceSessionID holds the value of the "source_session_id" field.
	SourceSessionID string `json:"source_session_id,omitempty"`
	// SourceTurnID holds the value of the "source_turn_id" field.
	SourceTurnID *string `json:"source_turn_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// StoppedAt holds the value of the "stopped_at" field.
	StoppedAt time.Time `json:"stopped_at,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// Cwd holds the value of the "cwd" field.
	Cwd *string `json:"cwd,omitempty"`
	// Prompts holds the value of the "prompts" field.
	Prompts jsontext.Value `json:"prompts,omitempty"`
	// Response holds the value of the "response" field.
	Response jsontext.Value `json:"response,omitempty"`
	// CaptureStatus holds the value of the "capture_status" field.
	CaptureStatus string `json:"capture_status,omitempty"`
	// PromptCount holds the value of the "prompt_count" field.
	PromptCount int `json:"prompt_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DesktopConversationRecordQuery when eager-loading is set.
	Edges        DesktopConversationRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DesktopConversationRecordEdges holds the relations/edges for other nodes in the graph.
type DesktopConversationRecordEdges struct {
	// Organization holds the value of the organization edge.
	Organization *DesktopOrganization `json:"organization,omitempty"`
	// Member holds the value of the member edge.
	Member *DesktopMember `json:"member,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopConversationRecordEdges) OrganizationOrErr() (*DesktopOrganization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: desktoporganization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// MemberOrErr returns the Member value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopConversationRecordEdges) MemberOrErr() (*DesktopMember, error) {
	if e.Member != nil {
		return e.Member, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: desktopmember.Label}
	}
	return nil, &NotLoadedError{edge: "member"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DesktopConversationRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case desktopconversationrecord.FieldPrompts, desktopconversationrecord.FieldResponse:
			values[i] = new([]byte)
		case desktopconversationrecord.FieldID, desktopconversationrecord.FieldOrganizationID, desktopconversationrecord.FieldMemberID, desktopconversationrecord.FieldPromptCount:
			values[i] = new(sql.NullInt64)
		case desktopconversationrecord.FieldClient, desktopconversationrecord.FieldSourceSessionID, desktopconversationrecord.FieldSourceTurnID, desktopconversationrecord.FieldCwd, desktopconversationrecord.FieldCaptureStatus:
			values[i] = new(sql.NullString)
		case desktopconversationrecord.FieldStartedAt, desktopconversationrecord.FieldStoppedAt, desktopconversationrecord.FieldReceivedAt:
			values[i] = new(sql.NullTime)
		case desktopconversationrecord.FieldRecordID, desktopconversationrecord.FieldInstallationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DesktopConversationRecord fields.
func (_m *DesktopConversationRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case desktopconversationrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case desktopconversationrecord.FieldRecordID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field record_id", values[i])
			} else if value != nil {
				_m.RecordID = *value
			}
		case desktopconversationrecord.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.Int64
			}
		case desktopconversationrecord.FieldMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				_m.MemberID = value.Int64
			}
		case desktopconversationrecord.FieldInstallationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field installation_id", values[i])
			} else if value != nil {
				_m.InstallationID = *value
			}
		case desktopconversationrecord.FieldClient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client", values[i])
			} else if value.Valid {
				_m.Client = value.String
			}
		case desktopconversationrecord.FieldSourceSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_session_id", values[i])
			} else if value.Valid {
				_m.SourceSessionID = value.String
			}
		case desktopconversationrecord.FieldSourceTurnID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_turn_id", values[i])
			} else if value.Valid {
				_m.SourceTurnID = new(string)
				*_m.SourceTurnID = value.String
			}
		case desktopconversationrecord.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case desktopconversationrecord.FieldStoppedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field stopped_at", values[i])
			} else if value.Valid {
				_m.StoppedAt = value.Time
			}
		case desktopconversationrecord.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case desktopconversationrecord.FieldCwd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cwd", values[i])
			} else if value.Valid {
				_m.Cwd = new(string)
				*_m.Cwd = value.String
			}
		case desktopconversationrecord.FieldPrompts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field prompts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Prompts); err != nil {
					return fmt.Errorf("unmarshal field prompts: %w", err)
				}
			}
		case desktopconversationrecord.FieldResponse:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Response); err != nil {
					return fmt.Errorf("unmarshal field response: %w", err)
				}
			}
		case desktopconversationrecord.FieldCaptureStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capture_status", values[i])
			} else if value.Valid {
				_m.CaptureStatus = value.String
			}
		case desktopconversationrecord.FieldPromptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_count", values[i])
			} else if value.Valid {
				_m.PromptCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DesktopConversationRecord.
// This includes values selected through modifiers, order, etc.
func (_m *DesktopConversationRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the DesktopConversationRecord entity.
func (_m *DesktopConversationRecord) QueryOrganization() *DesktopOrganizationQuery {
	return NewDesktopConversationRecordClient(_m.config).QueryOrganization(_m)
}

// QueryMember queries the "member" edge of the DesktopConversationRecord entity.
func (_m *DesktopConversationRecord) QueryMember() *DesktopMemberQuery {
	return NewDesktopConversationRecordClient(_m.config).QueryMember(_m)
}

// Update returns a builder for updating this DesktopConversationRecord.
// Note that you need to call DesktopConversationRecord.Unwrap() before calling this method if this DesktopConversationRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DesktopConversationRecord) Update() *DesktopConversationRecordUpdateOne {
	return NewDesktopConversationRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DesktopConversationRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DesktopConversationRecord) Unwrap() *DesktopConversationRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DesktopConversationRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DesktopConversationRecord) String() string {
	var builder strings.Builder
	builder.WriteString("DesktopConversationRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("record_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecordID))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberID))
	builder.WriteString(", ")
	builder.WriteString("installation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstallationID))
	builder.WriteString(", ")
	builder.WriteString("client=")
	builder.WriteString(_m.Client)
	builder.WriteString(", ")
	builder.WriteString("source_session_id=")
	builder.WriteString(_m.SourceSessionID)
	builder.WriteString(", ")
	if v := _m.SourceTurnID; v != nil {
		builder.WriteString("source_turn_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("stopped_at=")
	builder.WriteString(_m.StoppedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Cwd; v != nil {
		builder.WriteString("cwd=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("prompts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Prompts))
	builder.WriteString(", ")
	builder.WriteString("response=")
	builder.WriteString(fmt.Sprintf("%v", _m.Response))
	builder.WriteString(", ")
	builder.WriteString("capture_status=")
	builder.WriteString(_m.CaptureStatus)
	builder.WriteString(", ")
	builder.WriteString("prompt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromptCount))
	builder.WriteByte(')')
	return builder.String()
}

// DesktopConversationRecords is a parsable slice of DesktopConversationRecord.
type DesktopConversationRecords []*DesktopConversationRecord
