// Code generated by ent, DO NOT EDIT.

package desktopupdaterelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the desktopupdaterelease type in the database.
	Label = "desktop_update_release"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldArtifacts holds the string denoting the artifacts field in the database.
	FieldArtifacts = "artifacts"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldPublishedBy holds the string denoting the published_by field in the database.
	FieldPublishedBy = "published_by"
	// FieldWithdrawnBy holds the string denoting the withdrawn_by field in the database.
	FieldWithdrawnBy = "withdrawn_by"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldWithdrawnAt holds the string denoting the withdrawn_at field in the database.
	FieldWithdrawnAt = "withdrawn_at"
	// FieldWithdrawalReason holds the string denoting the withdrawal_reason field in the database.
	FieldWithdrawalReason = "withdrawal_reason"
	// Table holds the table name of the desktopupdaterelease in the database.
	Table = "desktop_update_releases"
)

// Columns holds all SQL columns for desktopupdaterelease fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublicID,
	FieldVersion,
	FieldNotes,
	FieldArtifacts,
	FieldStatus,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldPublishedBy,
	FieldWithdrawnBy,
	FieldPublishedAt,
	FieldWithdrawnAt,
	FieldWithdrawalReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the DesktopUpdateRelease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByPublishedBy orders the results by the published_by field.
func ByPublishedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedBy, opts...).ToFunc()
}

// ByWithdrawnBy orders the results by the withdrawn_by field.
func ByWithdrawnBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWithdrawnBy, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByWithdrawnAt orders the results by the withdrawn_at field.
func ByWithdrawnAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWithdrawnAt, opts...).ToFunc()
}

// ByWithdrawalReason orders the results by the withdrawal_reason field.
func ByWithdrawalReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWithdrawalReason, opts...).ToFunc()
}
