// Code generated by ent, DO NOT EDIT.

package desktopmember

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the desktopmember type in the database.
	Label = "desktop_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameNormalized holds the string denoting the name_normalized field in the database.
	FieldNameNormalized = "name_normalized"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAuthVersion holds the string denoting the auth_version field in the database.
	FieldAuthVersion = "auth_version"
	// FieldAPIKeySuspendedByOrganization holds the string denoting the api_key_suspended_by_organization field in the database.
	FieldAPIKeySuspendedByOrganization = "api_key_suspended_by_organization"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// EdgeAPIKeyAssignments holds the string denoting the api_key_assignments edge name in mutations.
	EdgeAPIKeyAssignments = "api_key_assignments"
	// Table holds the table name of the desktopmember in the database.
	Table = "desktop_members"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "desktop_members"
	// OrganizationInverseTable is the table name for the DesktopOrganization entity.
	// It exists in this package in order to avoid circular dependency with the "desktoporganization" package.
	OrganizationInverseTable = "desktop_organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
	// APIKeyAssignmentsTable is the table that holds the api_key_assignments relation/edge.
	APIKeyAssignmentsTable = "desktop_member_api_keys"
	// APIKeyAssignmentsInverseTable is the table name for the DesktopMemberAPIKey entity.
	// It exists in this package in order to avoid circular dependency with the "desktopmemberapikey" package.
	APIKeyAssignmentsInverseTable = "desktop_member_api_keys"
	// APIKeyAssignmentsColumn is the table column denoting the api_key_assignments relation/edge.
	APIKeyAssignmentsColumn = "member_id"
)

// Columns holds all SQL columns for desktopmember fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldPublicID,
	FieldOrganizationID,
	FieldName,
	FieldNameNormalized,
	FieldPhone,
	FieldStatus,
	FieldAuthVersion,
	FieldAPIKeySuspendedByOrganization,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// NameNormalizedValidator is a validator for the "name_normalized" field. It is called by the builders before save.
	NameNormalizedValidator func(string) error
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultAuthVersion holds the default value on creation for the "auth_version" field.
	DefaultAuthVersion int64
	// AuthVersionValidator is a validator for the "auth_version" field. It is called by the builders before save.
	AuthVersionValidator func(int64) error
	// DefaultAPIKeySuspendedByOrganization holds the default value on creation for the "api_key_suspended_by_organization" field.
	DefaultAPIKeySuspendedByOrganization bool
)

// OrderOption defines the ordering options for the DesktopMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameNormalized orders the results by the name_normalized field.
func ByNameNormalized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameNormalized, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAuthVersion orders the results by the auth_version field.
func ByAuthVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthVersion, opts...).ToFunc()
}

// ByAPIKeySuspendedByOrganization orders the results by the api_key_suspended_by_organization field.
func ByAPIKeySuspendedByOrganization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeySuspendedByOrganization, opts...).ToFunc()
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeyAssignmentsCount orders the results by api_key_assignments count.
func ByAPIKeyAssignmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeyAssignmentsStep(), opts...)
	}
}

// ByAPIKeyAssignments orders the results by api_key_assignments terms.
func ByAPIKeyAssignments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyAssignmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
func newAPIKeyAssignmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyAssignmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeyAssignmentsTable, APIKeyAssignmentsColumn),
	)
}
